// Phase 3 write-up builder (docx-js), mirroring build_phase2.js.
// Generates EIGENNEXUS_Phase3_Content.docx from the Phase 3 draft prose.
// [QBRAID-RUN] placeholders are styled (bold italic, dark red) so the GPU/QPU numbers
// owed are unmistakable and easy to find-and-replace once executed.
const { Document, Packer, Paragraph, TextRun, Table, TableRow, TableCell,
        AlignmentType, BorderStyle, WidthType, ShadingType, ImageRun } = require('docx');
const fs = require('fs');

const FONT="Times New Roman", SZ=22; // 11pt
const bd={style:BorderStyle.SINGLE,size:1,color:"888888"};
const borders={top:bd,bottom:bd,left:bd,right:bd};
const cw=9792;

function P(runs,opts={}){return new Paragraph({spacing:{after:opts.after??44,line:226,lineRule:"auto"},alignment:opts.align,...opts,children:Array.isArray(runs)?runs:[runs]});}
function T(t,o={}){return new TextRun({text:t,font:FONT,size:SZ,bold:o.b,italics:o.i});}
function Q(t){return new TextRun({text:t,font:FONT,size:SZ,bold:true,italics:true,color:"A52A2A"});} // [QBRAID-RUN] placeholder
function H(t){return new Paragraph({spacing:{before:64,after:32,line:226,lineRule:"auto"},children:[new TextRun({text:t,font:FONT,size:SZ,bold:true})]});}

function cell(text,w,{hdr=false,bold=false,align=AlignmentType.LEFT}={}){
  return new TableCell({borders,width:{size:w,type:WidthType.DXA},
    shading:{fill:hdr?"D5E8F0":"FFFFFF",type:ShadingType.CLEAR},
    margins:{top:40,bottom:40,left:90,right:90},
    children:[new Paragraph({alignment:align,spacing:{after:0,line:240,lineRule:"auto"},
      children:[new TextRun({text:text,font:FONT,size:21,bold:hdr||bold})]})]});
}
function row(cells,w,opts={}){return new TableRow({children:cells.map((c,i)=>cell(c,w[i],opts))});}

// Table 1: verified results (5a) — quantum vs classical, matched instances
const w1=[2000,1100,2900,2400,1392];
const tbl1=new Table({width:{size:9792,type:WidthType.DXA},columnWidths:w1,rows:[
  row(["System","Qubits","Quantum (GQE/QSCI)","Classical ref.","Notes"],w1,{hdr:true,align:AlignmentType.CENTER}),
  row(["H₂/H₄/H₆","4/8/12","0.000 / 0.009 / 0.297 mHa","FCI (exact)","two-stage GQE (UCCSD)"],w1,{align:AlignmentType.CENTER}),
  row(["H₆ GQE→QSCI","12","1.05 mHa (51→1.05, ~50×)","FCI","measured pipeline"],w1,{align:AlignmentType.CENTER}),
  row(["H₁₀/H₁₄","20/28","0.57 / 1.21 mHa","FCI / CCSD(T)","2,401 / 18,201 dets"],w1,{align:AlignmentType.CENTER}),
  row(["CrO ⁵Π / NiO ³Σ⁻","20","0.038 / 0.197 mHa","CASCI (exact)","open-shell multiref."],w1,{align:AlignmentType.CENTER}),
  row(["SnO / SnO₂","16/20","chem. acc. ≤1.6 (obs. 0.11–0.46 / 0.13–0.23)","FCI","EUV target; values version/run sensitive"],w1,{align:AlignmentType.CENTER}),
  row(["Noise (H₁₀)","20","≤3.3 mHa @ 30% corrupt (2×10⁶ shots)","—","noise-aware bonus"],w1,{align:AlignmentType.CENTER}),
]});

// Table 2: classical baseline & exact wall (5b) — timed, matched instances
const w2=[1700,1300,2400,2300,2092];
const tbl2=new Table({width:{size:9792,type:WidthType.DXA},columnWidths:w2,rows:[
  row(["System","Qubits","FCI (exact) wall-clock","CCSD(T) err vs FCI","CCSD(T) wall-clock"],w2,{hdr:true,align:AlignmentType.CENTER}),
  row(["H₆","12","0.08 s","0.026 mHa","0.09 s"],w2,{align:AlignmentType.CENTER}),
  row(["H₁₀","20","0.74 s","0.173 mHa","0.15 s"],w2,{align:AlignmentType.CENTER}),
  row(["H₁₂","24","5.02 s","0.282 mHa","0.17 s"],w2,{align:AlignmentType.CENTER}),
  row(["H₁₄","28","minutes","—","~0.2 s"],w2,{align:AlignmentType.CENTER}),
  row(["H₁₆+","32+","intractable (CPU)","—","—"],w2,{align:AlignmentType.CENTER}),
]});

const children=[
  new Paragraph({spacing:{after:30,line:240,lineRule:"auto"},alignment:AlignmentType.CENTER,
    children:[new TextRun({text:"MATGEN-Q: Scaling a Two-Stage Generative Quantum Eigensolver to 40 Qubits on NVIDIA CUDA-Q for EUV Photoresist Chemistry",font:FONT,size:24,bold:true})]}),
  new Paragraph({spacing:{after:80,line:240,lineRule:"auto"},alignment:AlignmentType.CENTER,
    children:[new TextRun({text:"Team EIGENNEXUS  —  Advanced Materials (Mitsubishi Chemical Group & AIST)  —  GIC 2026 Phase 3",font:FONT,size:21,italics:true})]}),

  new Paragraph({spacing:{after:60,line:226,lineRule:"auto"},alignment:AlignmentType.JUSTIFIED,indent:{left:360,right:360},children:[
    new TextRun({text:"Abstract. ",font:FONT,size:21,bold:true}),
    new TextRun({text:"Molecular ground-state energies underlie reaction thermodynamics, redox behaviour, and materials screening, and they are exactly where classical methods break down under strong correlation. MATGEN-Q is a two-stage generative quantum eigensolver (a classical transformer proposes the circuits, QSCI evaluates them) scaled toward the 40-qubit, industrially relevant regime on NVIDIA CUDA-Q, targeting EUV photoresist chemistry. The results are executed and reproducible: chemical accuracy on the multireference oxides CrO/NiO and the EUV Sn-oxides at 20 qubits; a 40-qubit flagship at 1.226 mHa against a reference frozen before access; two 38-qubit runs that correct their own DMRG references; and an independent DMRG extrapolation placing the flagship 1.59 mHa from the near-exact limit. Where stretched-bond CCSD(T) turns confidently wrong, sitting below the exact energy with no warning, QSCI stays a variational, self-certifying bound. We claim no quantum advantage: every result is classical simulation, GPU determinant-space computation, or small-scale QPU validation, and one command reproduces all 26 checks (26/26 PASS).",font:FONT,size:21}),
  ]}),

  H("1. Focus Area and Rationale"),
  P([T("Ground-state energy estimation underlies reaction thermodynamics, redox behavior, and excited-state properties across materials chemistry, yet classical cost grows exponentially with electron correlation and the gold-standard CCSD(T) scales O(N⁷). The Generative Quantum Eigensolver (GQE; Nakaji et al. 2024) departs from VQE: a classical generative transformer proposes the circuits rather than optimizing a variational one, sidestepping barren plateaus (Tilly et al. 2022; a GQE property established by Nakaji et al., adopted here, not re-demonstrated). Statevector GQE has stayed small-scale, and QSCI-paired GQE had reached 32 qubits (Kemmoku, Gao et al. 2026). "),T("Carrying this generative approach into the ~40-qubit, industrially relevant regime, executed and reproducible, is the problem Phase 3 addresses.",{b:true}),T(" Our primary contribution is quantum-accurate energies where the classical gold standard breaks down: as bonds stretch, single-reference CCSD(T) collapses non-variationally below the exact energy with no internal warning. We therefore target the open-shell multireference oxides CrO and NiO and the EUV-relevant SnO and SnO₂ at 20 qubits, validated against exact diagonalization and third-party HamLib Hamiltonians, and around that core build the machinery to scale (tensor-network plus selected-CI evaluation, MP2 pool compression, and a generator that transfers across size and chemistry), aimed at the 40q+ regime.")]),
  P([T("Our application target is EUV semiconductor photoresist chemistry (tin-oxo clusters; Sn, Hf, Zr oxides), whose open-shell multireference character defeats single-reference classical methods, and the focus of an active quantum-simulation program by one of this challenge's providers (Kharazi et al., Xanadu & Mitsubishi Chemical, 2026). Figure 1 (§5) shows the stakes on a real Cr–O stretch: in-active-space CCSD(T) turns erratic, up to ~144 mHa off and often non-convergent, while the variational selected-CI/QSCI selector stays a self-certifying bound within chemical accuracy. The pipeline (AI proposes, classical screens, GQE/QSCI refines, Bayesian selects) carries over to the battery electrolytes, catalysts, and polymers central to Mitsubishi Chemical and AIST; in an $800B+ semiconductor industry, the multi-fidelity screening economics of Fare et al. (2022) are the cost lever MATGEN-Q pulls through quantum-accurate pre-selection.")]),
  P([T("Stakeholder relevance. ",{b:true}),T("For Mitsubishi Chemical: a quantum-accurate, self-certifying filter ahead of costly synthesis and lithographic testing, where single-reference methods misjudge strongly-correlated tin-oxo energetics. For AIST/G-QuAT: a scalable, reproducible GQE workflow on CUDA-Q that extends the jointly-developed program past its current size limits.")]),

  H("2. Target System and Data Modeling Strategy"),
  P([T("Scaling vehicle. ",{b:true}),T("The Hₙ chain series (n = 2…20; 4–40 qubits, STO-6G, Jordan–Wigner) is the canonical strong-correlation benchmark: one bond-length parameter tunes it from weak to strong correlation, stressing the simulation layer any scaling claim rests on.")]),
  P([T("Target chemistry. ",{b:true}),T("The same QSCI engine reaches chemical accuracy on real materials chemistry. On Sn-oxide active spaces (Sn ECP-CASCI, validated on H₄ to 0.0000 mHa) it holds chemical accuracy for SnO (16q) and SnO₂ (20q): reproduce.py asserts ≤1.6 mHa; we observe 0.11–0.46 / 0.13–0.23 across versions and re-runs. To reach a genuine EUV motif rather than a diatomic, we also treat a bridged "),T("Sn–O–Sn tin-oxo fragment (Sn₂O₂ rhombus) to 0.41 mHa at 16q",{b:true}),T(", and the open-shell multireference "),T("CrO ⁵Π (0.038 mHa) and NiO ³Σ⁻ (0.197 mHa) at 20 qubits",{b:true}),T(", all executed results. The 38-qubit regime is a GPU scaling target in §5, not a pre-claimed number; it supersedes the aspirational ≤0.08 mHa @38q figure in our Phase 2 draft, which we no longer claim.")]),
  P([T("Data integrity. ",{b:true}),T("We adopt HamLib (Sawaya et al., Quantum 2024) and replicate its generation methodology (PySCF, OpenFermion, Jordan–Wigner, STO-6G). "),T("Against the published files, our FCI reproduces to 0.00000 mHa (H₂–H₆), and at 28/32/40 qubits our Hamiltonians match HamLib exactly in term count (27,735 / 47,489 / 116,577) and to ~15 significant figures in coefficient magnitude",{b:true}),T(", differing only by a spectrum-invariant orbital-phase convention.")]),
  P([T("Accuracy anchors. ",{b:true}),T("FCI exactly (≤20q), CCSD(T) near equilibrium, and under strong correlation, where CCSD(T) breaks down, DMRG, verified to reproduce FCI to 0.000 mHa at 20q.")]),

  H("3. GQE-Based Approach and Algorithmic Innovation"),
  P([T("MATGEN-Q is a two-stage GQE. "),T("Stage 1: ",{b:true}),T("a decoder-only GPT-style transformer, trained by sequence–energy matching (Nakaji et al.), writes circuits as token sequences over a UCC single/double excitation pool. "),T("Stage 2: ",{b:true}),T("adjoint-gradient angle optimization converges them to chemical accuracy. Four design choices make it scale:")]),
  P([T("(1) Tensor-network (MPS) simulation, the GPU scaling enabler, its bond-dimension argument demonstrated on CPU. ",{b:true}),T("CUDA-Q's tensornet-mps memory scales with entanglement, not 2ⁿ; block2 DMRG verifies the enabling claim: "),T("χ for chemical accuracy grows only modestly with size (χ≈50/100/400 at 20/28/40 qubits), area-law-bounded near equilibrium (Sₘₐₓ 0.39), rising into strong correlation (Sₘₐₓ 4.43)",{b:true}),T(". At 40q, χ≈400 keeps the MPS footprint (~n·χ²·d, megabytes) far below the ~16 TB exact statevector. The 20q/28q GPU runs are executed to chemical accuracy (§5); the full 40q tensornet-mps run remains the primary owed deliverable, de-risked by the measured χ target and the ≈5× faster growth engine.")],{after:30}),
  P([T("(2) QSCI energy evaluation, accuracy- and noise-aware. ",{b:true}),T("In Quantum-Selected Configuration Interaction (Kanno et al. 2023), dominant configurations are sampled from the generated circuit and H is classically diagonalized in that subspace. Because the device defines only the subspace, the method is intrinsically noise-robust: at 20q with 2×10⁶ shots the energy degrades gracefully to ≤3.3 mHa with 30% of measurements corrupted, and through CUDA-Q's density-matrix backend with a physical depolarizing channel, QSCI on H₄ holds chemical accuracy to 5% per-gate noise; we read this as a selection-principle robustness check on a small determinant space, not a hardware forecast.")],{after:30}),
  P([T("(3) Operator-pool compression, for efficiency. ",{b:true}),T("Ranking the O(N⁴) double-excitation pool by active-space MP2 amplitude and keeping the top fraction shrinks the transformer vocabulary with negligible accuracy loss, exactly where random pruning collapses: in a deterministic CI-subspace test (CO/N₂/SiO, 12q), "),T("N₂ retains full-pool accuracy (2.26 mHa) keeping only 25% of doubles (vocabulary 1170→430), vs 50.4 mHa for random pruning at the same size (~22×)",{b:true}),T("; CO holds 3.7 mHa at 40% kept vs 29.7 mHa random.")],{after:30}),
  P([T("(4) Distributed hybrid workflow, ",{b:true}),T("detailed in §4.")],{after:30}),
  P([T("Transfer learning: a generative prior that carries across system size and chemistry. ",{b:true}),T("A canonical, frontier-relative tokenization (each excitation encoded as occupied-depth-below-HOMO and virtual-height-above-LUMO, independent of qubit count) makes a small system's token vocabulary a provable subset of a larger one (H₆/12q ⊂ H₈/16q ⊂ H₁₀/20q), so one GPT-QE generator trained only on H₄+H₆ (8q+12q) deploys zero-shot across 16→56 qubits. "),T("The robust signals are statistical: ~3.6× tighter selection spread than random (≈1.4 vs ≈5.1 mHa across-seed SD) and 43/48 size×seed paired wins at 8 seeds (binomial p<0.0001)",{b:true}),T("; reliable selection, not a lottery. The per-size mean advantage stays positive and significant (7/8 wins) through 56q, narrowing only in magnitude (+7.1→+3.9 mHa, 16→56q). Trained on energy alone, the policy recovers the MP2 double-excitation amplitude hierarchy (Spearman ρ=0.31, p<0.002; 4 of its top-8 doubles are MP2's); it has learned real chemistry. This is the "),T("train-small, deploy-large",{i:true}),T(" idea. GQE training is CPU-bound near ~16 qubits, so transferring a small-trained generator toward the 40q+ target, instead of training at scale, speaks directly to the scalability criterion. 56q is reachable on CPU through a determinant-space evaluation (each excitation maps by bitmask to a determinant, diagonalized via Slater-Condon, validated to 0.0000 mHa against Jordan–Wigner) that needs no 2ⁿ statevector, a "),T("selected-CI proxy",{i:true}),T(" for circuit-sampled QSCI: relative at a small fixed budget (K=96; the generator beats random at every budget up to K=96, converging with it by K=128), not absolute chemical accuracy. ")]),
  P([T("Cross-chemistry transfer (honest, partial). ",{b:true}),T("On oxide active spaces the same generator beats random on 3 of 6 targets (CO-12q/SiO/CO-20q), ties BeO, loses on SnO; target-specific MP2 is strongest everywhere. Cross-size transfer is robust, cross-chemistry only where the target resembles training: a zero-cost prior, not a universal one. A same-size conditional-GQE variant (cf. Minami, Nakaji et al. 2025) gave only a within-noise gain, also reported as a negative.")]),


  H("4. Hybrid Architecture"),
  P([T("The classical transformer trains on GPU (PyTorch); circuit evaluations are dispatched across GPUs through CUDA-Q's mqpu in an asynchronous generate→evaluate→update loop. Quantum resources handle state preparation and energy estimation (MPS/QSCI); classical resources handle generation, optimization, and active-space selection. "),T("The execution path is validated on CUDA-Q itself: the UCCSD/QSCI pipeline reproduces exact FCI on H₄ through the qpp-cpu backend (VQE within 0.02 mHa via cudaq.observe, QSCI within chemical accuracy via cudaq.sample), confirming the generated circuits compile and sample through the SDK. The full QPU submission chain (export→submit→decode→QSCI) runs end-to-end through the qBraid cloud runtime on its free simulator tier (+2.0 mHa vs FCI, job IDs committed); 20q/28q are executed on NVIDIA hardware and AQT trapped-ion silicon decoded clean (§5); the 40q tensornet-mps run is owed.",{b:true})]),

  H("5. Phase 3 Execution and Results"),
  P([T("Verified results (CPU).",{b:true}),T(" One command ("),T("reproduce.py",{i:true}),T(") runs 26 automated checks: 17 re-executions plus 9 committed-artifact audits, among them the pre-registration SHA-256, the AQT decode, and a cost audit re-deriving program spend from published pricing and committed configs. The result is "),T("26/26 PASS",{b:true}),T(", every value tracing to a committed result file (Table 1).")],{after:50}),
  tbl1,
  new Paragraph({spacing:{before:30,after:50,line:240,lineRule:"auto"},children:[new TextRun({text:"Table 1. Verified quantum results vs classical references on matched instances (CPU).",font:FONT,size:19,italics:true})]}),
  P([T("Classical baseline and the exact wall (matched instances, timed). ",{b:true}),T("On identical STO-6G Hₙ geometries, FCI wall-clock grows steeply (~6.8× from 20→24 qubits, 0.74→5.02 s single-thread) and is CPU-intractable by 32q. CCSD(T) stays cheap but its error climbs with correlation and breaks down under strong correlation (at H₂₄/48q, classical DMRG is itself 6.83 mHa off CCSD(T)). At 40q the exact statevector needs ~16 TB vs ~0.2 GB for the MPS tier (measured χ=400); full CI needs ~3×10¹⁰ determinants vs ~10⁶ for QSCI. These are the walls the MPS and QSCI tiers remove (Table 2; quantified in results/crossover).")],{after:50}),
  tbl2,
  new Paragraph({spacing:{before:30,after:50,line:240,lineRule:"auto"},children:[new TextRun({text:"Table 2. Classical reference cost on the Hₙ ladder (single-thread CPU; wall-clocks machine-dependent, reproduced in classical_baselines_evidence.json — the steep growth and exact-method wall, not absolute seconds, are the claim; H₁₄+ rows qualitative).",font:FONT,size:19,italics:true})]}),
  P([T("Executed on qBraid GPU (real hardware runs, corrected incremental engine). ",{b:true}),T("Each run below was judged against a reference committed before access (git-timestamped preregistration). "),
     T("20q H₁₀ (cuStateVec) ",{b:true}),T("reproduces full CI to "),T("+0.000 mHa",{b:true}),T(" at 0.44 GB device memory, an exact GPU-execution anchor. "),
     T("28q H₁₄ (cuStateVec), ",{b:true}),T("device-sampled QSCI grown to 64,212 determinants, reaches "),T("+0.395 mHa vs block2 DMRG(χ=400)",{b:true}),T(" at 2.82 GB: chemical accuracy above the 20q scale on hardware. Both meet their pre-registered energy (P1) and device-memory (P3) criteria. "),
     T("40q H₂₀ (primary criterion): ",{b:true}),T("the fast incremental engine drives the QSCI error "),T("monotonically 8.9→3.2→1.226 mHa as the budget grows 30k→150k→450,257 determinants",{b:true}),T(" (~(dets)⁻⁰·⁷), meeting the pre-registered P1 chemical-accuracy criterion against the committed DMRG(χ=400) reference (P2's determinant band also met, ahead of its ~10⁶-det estimate). The run stopped at iter-3 on a disk ceiling, disclosed in-evidence; QSCI being variational, an early stop can only worsen a pass, never manufacture one (attempt-1's old engine stalled at 6k/+14.8 mHa). Absolute accuracy against a stricter χ=800 reference (+2.19 mHa) is the job of E3/E6, below. The subspace is MP2-seeded (the tensornet-mps sampler's fixed contraction cost is impractical at 40q); growth is seed-independent, and the device sampler is proven exact at 20q/28q. "),
     T("CrO near-38q, where we corrected the classical reference (Figure 2): ",{b:true}),T("QSCI on CrO CAS(18,19)=38q converged "),T("−3.784 mHa BELOW the same-CAS DMRG(χ=400) reference",{b:true}),T(" (529,392 determinants, 19.1 h; reference committed before access). Both are "),T("variational upper bounds on the identical Hamiltonian",{b:true}),T(", so the lower energy is strictly more accurate; the pre-registered χ-escalation confirms it. This is the P4 criterion FAILING as-measured (|Δ|>1.6 mHa): it assumed DMRG(χ=400) was truth, and the result disproved that. "),T("The mechanism is measured: ",{b:true}),T("against exact FCI at 20q, truncation error at fixed χ grows ~2,000× into strong correlation; χ=400, exact at 20q, is ≥0.92 mHa off at 40q; a χ validated on a smaller system does not transfer (reference_reliability_map.py). "),
     T("Real-QPU silicon (10–16q), executed and decoded: ",{b:true}),T("the 3-job pooled protocol ran end-to-end through qBraid (qir-sv tier: +2.0 mHa vs FCI, PASS, job IDs committed); the trapped-ion flight (AQT ibex-q1, 2,000 shots/job, SHA-pinned exports) decoded 2026-07-20. Number-conserving post-selection kept 28.6% / 25.1% of shots, device-sampled determinants give +20.4 / +11.1 mHa, and device-seeded QSCI growth recovers exact FCI (0.000 mHa): genuine trapped-ion samples driving the same machinery as the 40q runs.")]),
  P([T("What the results establish. ",{b:true}),T("Correctness: the pipeline reproduces the FCI/CASCI reference to chemical accuracy on every instance we can run, including the multireference oxides and EUV Sn-oxides. Scalability: chemical accuracy on a vanishing fraction of the CI space (3.8% at 20q, 0.15% at 28q). Transferable structure (§3). Boundaries in §7.")]),

  P([T("Where it matters most: trust under strong correlation. ",{b:true}),T("Stretching H₁₀ (20q) to dissociation drives genuine multireference character (the Hartree–Fock weight in the exact wavefunction falls 0.93→0.06), and here the classical gold standard fails qualitatively: CCSD(T) collapses "),T("non-variationally",{i:true}),T(" to 217 mHa BELOW the exact FCI energy at R=2.4 Å, confidently wrong and unphysical. The determinant-subspace method (the QSCI principle, here via iterative selected-CI) instead "),T("reaches chemical accuracy with only ~500 determinants",{b:true}),T(" at every geometry, as a variational bound that converges systematically. "),T("Nor is this a hydrogen-chain artifact: on a real Cr–O stretch (CrO ⁵Π, CAS(10,10)=20q), in-active-space CCSD(T) develops large, frequently non-convergent errors (tens to ~144 mHa vs exact CASCI, non-convergent points scattering on re-runs) as the dominant-determinant weight falls 0.87→0.16, while selected-CI/QSCI stays variational and within a few mHa throughout (Figure 1).",{b:true}),T(" We also certify the error rather than assert it: an Epstein–Nesbet PT2 correction tightens the bound toward FCI; "),T("E_var+PT2 is a second-order estimate (not a bound) that at our budgets converges to FCI from above",{b:true}),T(". The CIPSI extrapolation reproduces FCI to ~4 mHa near equilibrium (R²=0.999), degrading to ~54 mHa heavily stretched, which we report rather than hide. Even at R=2.4 Å (468 determinants), E_var+PT2 sits +10.9 mHa above FCI with the shrinking E_var↔E_var+PT2 gap as its convergence certificate, whereas CCSD(T) sits 217 mHa below with no error signal at all. (Selected-CI here is classical on CPU; QSCI is its device-driven instantiation, realized on GPU by the 28q run.) ",{}),T("R&D value: ",{b:true}),T("a classical energy that sits below the exact answer with no error flag commits multi-month synthesis spend to a false lead: the dominant hidden cost of discovery, and exactly what a self-certifying variational selector removes.")]),
  new Paragraph({keepNext:true,spacing:{before:40,after:8,line:240,lineRule:"auto"},alignment:AlignmentType.CENTER,
    children:[new ImageRun({type:"png",data:fs.readFileSync("../results/cro_dissociation.png"),transformation:{width:158,height:101}})]}),
  new Paragraph({spacing:{before:0,after:60,line:240,lineRule:"auto"},alignment:AlignmentType.CENTER,
    children:[new TextRun({text:"Figure 1. Trust on a real oxide. As the CrO ⁵Π bond stretches (left→right), in-active-space CCSD(T) becomes erratic and frequently non-convergent (open markers), a few to ~144 mHa vs exact CASCI, while selected-CI/QSCI stays a variational bound within chemical accuracy (≤2.8 mHa). CCSD(T) uses the identical embedded Hamiltonian as CASCI (apples-to-apples).",font:FONT,size:18,italics:true})]}),
  new Paragraph({keepNext:true,spacing:{before:40,after:8,line:240,lineRule:"auto"},alignment:AlignmentType.CENTER,
    children:[new ImageRun({type:"png",data:fs.readFileSync("../results/chi_ladder_correction.png"),transformation:{width:140,height:81}})]}),
  new Paragraph({spacing:{before:0,after:60,line:240,lineRule:"auto"},alignment:AlignmentType.CENTER,
    children:[new TextRun({text:"Figure 2. Correcting the classical reference at 38q. Escalating the bond dimension walks DMRG down toward our QSCI energy (+3.78 → +1.06 → +0.36 mHa at χ=400/800/1200), never crossing it. Both bound the same CAS(18,19) Hamiltonian from above, so the lower energy is strictly more accurate: the committed χ=400 reference carried a silent truncation error. Selection is classical at this size (disclosed proxy; device-sampled at 20q/28q).",font:FONT,size:18,italics:true})]}),
  P([T("Frozen extension campaign (E2–E6; executed 2026-07-23/24). ",{b:true}),T("Protocols were git-timestamped before access (preregistration_v2.json + _e67_supplementary.json) and reported as measured: pass, fail, or resource-DNF. "),
     T("E4, a second reference correction on the real EUV motif: ",{b:true}),T("QSCI on the committed Sn₂O₂ rhombus (CAS(18,19)=38q) converged "),T("−0.399 mHa BELOW the same-CAS DMRG(χ=400) reference",{b:true}),T(" (524,764 dets, 7.4 h; reference committed pre-run), reproducing the correction on the actual tin-oxo chemistry. "),
     T("EUV-motif trust curve: ",{b:true}),T("stretching the Sn₂O₂ Sn–O bridge 2.05→3.28 Å into the cleavage regime grows in-active-space CCSD(T) error "),T("0.14→5.49 mHa (~40×)",{b:true}),T(" while the identical selected-CI/QSCI stays variational (≤0.48 mHa) as the dominant-determinant weight collapses 0.95→0.53: Figure 1's trust story on the real motif. "),
     T("E3, the 40q absolute-certification protocol (terminal at it5): ",{b:true}),T("growth-to-PT2-certificate on H₂₀ 40q with bucket-parallel Epstein–Nesbet (bit-identical to serial), ended by an external pod kill during it6 growth (disclosed; not a convergence failure). At it5, "),T("E_var +0.185 mHa vs χ=400 (ii MET), 750,257 dets (iii MET)",{b:true}),T(", |PT2| converging cleanly 84→4.6→2.6→2.0→1.57→1.31 mHa; the |PT2|≤0.5 point (i, ~it10–11) went unreached, as-measured. "),
     T("E2, a resource-DNF (operational record, not the E2 result): ",{b:true}),T("the device-seeded 40q run (committed 102-det seed) needs ≥128 GiB and was OOM-killed at iter-3 cap-fill (peak 133.5 GB, 97%; two deterministic attempts). E4 completed on the same box at 59.7 GB, so +2 qubits doubles the footprint: an honest hardware ceiling, no tuning. "),
     T("E5, the least-grounded frontier (44q), non-converged and reported as such: ",{b:true}),T("H₂₂ 44q growth against a re-frozen χ=1200 judge, terminated early to protect E3's runway; the committed trajectory +125→+8.7→+5.2→+4.0 mHa decelerates but does not reach ≤1.6 mHa before the abort gate: the pre-registered expected outcome, no threshold moved, frozen parameters untouched. "),
     T("E6, an independent absolute-accuracy anchor (supplementary, pre-registered): ",{b:true}),T("high-χ DMRG (χ=400→2400) on the identical H₂₀/40q Hamiltonian, extrapolated on discarded weight to "),T("FCI(40q) = −10.293599 ± 0.022 mHa (R²=0.997)",{b:true}),T(", places E3's committed it5 variational energy "),T("+1.59 mHa from the near-exact limit, at the 1 kcal/mol edge and jackknife-robust to ±0.05 mHa",{b:true}),T(" (leave-one-out +1.55→+1.61 mHa; e6_jackknife.py). "),T("A second, independent route cross-validates it: ",{b:true}),T("extrapolating E3's own PT2 trace to PT2→0 (standard CIPSI, a different method class and extrapolation variable) gives −10.293621 Ha, "),T("agreeing with the DMRG route to 0.064 mHa in the worst fit window",{b:true}),T(" (~0.10 mHa, ~15× inside chemical accuracy with Route A's jackknife folded in). The 40q exact energy is pinned twice, independently (e3_cipsi_crossvalidation.py).")]),
  P([T("Proxy validated against real measurement; cost scaling. ",{b:true}),T("Measured QSCI (qml.sample, 3,000 shots × 160 circuits) at 16q/20q confirms the determinant-space proxy tracks the circuit-sampled pipeline: 28.1 vs 26.6 and 50.4 vs 49.3 mHa (at this shot budget diffuse random sampling edges out the generator, a low-shot coverage effect, not a quality reversal). Determinants for chemical accuracy grow ~1.38× per qubit against 2.0× for FCI (log R²=0.99): vanishing but still exponential, and we do not claim polynomial scaling.")]),

  H("6. Platform Use and Resourcing"),
  P([T("We run on "),T("NVIDIA H100/A100 (80 GB)",{b:true}),T(" with CUDA-Q: tensornet-mps for the 24–40q tier, cuStateVec for exact validation to ~32q, multi-GPU (NVLink) for distributed evaluation and the >40q bonus, and QPU access for the 10–16q validation. The ~16 TB exact statevector at 40q collapses onto a single 80 GB GPU through CUDA-Q MPS (~200× reduction), which is what makes the 40-qubit tier reachable.")]),
  P([T("Resource estimate. ",{b:true}),T("With pool compression, a length-8 UCC circuit is shallow (≤2-qubit gates) and within MPS reach near equilibrium; QSCI needs ~10³–10⁴ shots per circuit; the full 24→40q sweep plus oxide runs is roughly 1–2 weeks on one GPU. Measured timings: 20q 191 s, 28q 2,386 s; GPU sampling 1–32 s, the rest classical determinant growth (cut ≈5× by the incremental engine).")]),

  H("7. Limitations and Honest Scope"),
  P([T("Where the approach does and does not yet provide benefit: (i) ",{}),T("Measurement vs proxy: ",{b:true}),T("the GQE→QSCI loop is measured at 12q and device-sampled at 20q/28q on GPU (§5); larger QSCI numbers use a hardware-independent determinant-space proxy. (ii) ",{}),T("No classical-beating claim: ",{b:true}),T("classical FCI/DMRG solve every instance here, including the 40q flagship (our own DMRG anchor pins it, §5); we claim no speed or reach advantage, only correctness, self-certification, and favourable scaling. (iii) ",{}),T("40q absolute certification: ",{b:true}),T("the flagship meets its pre-registered relative criterion; E3 reached a terminal it5 (external pod kill) with prediction ii met and the |PT2|≤0.5 point unreached, reported as-measured (§5). (iv) ",{}),T("Transfer scope: ",{b:true}),T("cross-size transfer is significant at 8 seeds (43/48 wins, p<0.0001), narrowing in magnitude but positive through 56q; cross-chemistry wins 3 of 6 oxides (BeO a tie), fails on SnO, and target-specific MP2 beats the transferred prior: a zero-cost prior, not a universal or MP2-beating one.")]),

  H("8. Conclusion and Reproducibility"),
  P([T("MATGEN-Q contributes on four axes. "),
     T("AI: ",{b:true}),T("a classical generative transformer designs the circuits and "),T("transfers",{i:true}),T(": trained at 8q+12q, deployed zero-shot to 56q (43/48 wins, p<0.0001). "),
     T("Quantum: ",{b:true}),T("paired with QSCI and executed at scale: a 40q energy chemically accurate against its frozen reference, device-sampled 20q/28q GPU and trapped-ion runs, and two 38q runs that "),T("correct",{i:true}),T(" their DMRG references. "),
     T("Business: ",{b:true}),T("a pre-synthesis trust gate: where CCSD(T) is "),T("confidently wrong",{i:true}),T(", QSCI is variational and self-certifying, so synthesis spend is never committed to a false lead. "),
     T("Scientific: ",{b:true}),T("every judged claim pre-registered and reported as measured, including a resource-DNF, a non-convergence, and two claims we "),T("withdrew",{i:true}),T(", and one command ("),T("reproduce.py",{i:true}),T(", 26/26) re-runs every headline result.")]),

  new Paragraph({spacing:{before:120,after:40,line:240,lineRule:"auto"},pageBreakBefore:true,children:[new TextRun({text:"References",font:FONT,size:SZ,bold:true})]}),
];
function refP(n,txt){return new Paragraph({spacing:{after:30,line:240,lineRule:"auto"},indent:{left:360,hanging:360},children:[new TextRun({text:"["+n+"] ",font:FONT,size:20,bold:true}),new TextRun({text:txt,font:FONT,size:20})]});}
const refs=[
 refP(1,"K. Nakaji, L. B. Kristensen, J. A. Campos-Gonzalez-Angulo, M. Ghazi Vakili, H. Huang, M. Bagherimehrab, C. Gorgulla, F. Wong, A. McCaskey, J.-S. Kim, T. Nguyen, P. Rao, and A. Aspuru-Guzik, “The generative quantum eigensolver (GQE) and its application for ground state search,” arXiv:2401.09253 (2024)."),
 refP(2,"N. P. D. Sawaya, D. Marti-Dafcik, Y. Ho, D. P. Tabor, D. E. Bernal Neira, A. B. Magann, S. Premaratne, P. Dubey, A. Matsuura, N. Bishop, W. A. de Jong, S. Benjamin, O. Parekh, N. Tubman, K. Klymko, and D. Camps, “HamLib: A library of Hamiltonians for benchmarking quantum algorithms and hardware,” Quantum 8, 1559 (2024). DOI: 10.22331/q-2024-12-11-1559."),
 refP(3,"S. Minami, K. Nakaji, Y. Suzuki, A. Aspuru-Guzik, and T. Kadowaki, “Generative quantum combinatorial optimization by means of a novel conditional generative quantum eigensolver,” Digital Discovery 4(8), 2229–2243 (2025). DOI: 10.1039/D5DD00138B (arXiv:2501.16986)."),
 refP(4,"K. Kanno, M. Kohda, R. Imai, S. Koh, K. Mitarai, W. Mizukami, and Y. O. Nakagawa, “Quantum-Selected Configuration Interaction: classical diagonalization of Hamiltonians in subspaces selected by quantum computers,” arXiv:2302.11320 (2023)."),
 refP(5,"NVIDIA Corporation, “CUDA-Q (formerly CUDA Quantum) and the cuQuantum SDK: cuStateVec, tensornet, and tensornet-mps backends,” software (2024–2026). https://developer.nvidia.com/cuda-q."),
 refP(6,"J. Tilly, H. Chen, S. Cao, D. Picozzi, K. Setia, Y. Li, E. Grant, L. Wossnig, I. Rungger, G. H. Booth, and J. Tennyson, “The Variational Quantum Eigensolver: A review of methods and best practices,” Physics Reports 986, 1–128 (2022). DOI: 10.1016/j.physrep.2022.08.003."),
 refP(7,"C. Fare, P. Fenner, M. Benatan, et al., “A multi-fidelity machine learning approach to high-throughput materials screening,” npj Computational Materials 8, 257 (2022). DOI: 10.1038/s41524-022-00947-9."),
 refP(8,"T. D. Kharazi, S. Fomichev, S. Kanno, T. Kobayashi, J. M. Arrazola, Q. Gao, and T. F. Stetina, “Quantum Simulations for Extreme Ultraviolet Photolithography,” arXiv:2602.20234 (2026). [Xanadu & Mitsubishi Chemical Corporation — a challenge provider]"),
 refP(9,"R. Kemmoku, Q. Gao, S. Kanno, K. Keithley, I. Hamamura, N. Yamamoto, and K. Nakaji, “Generative Circuit Design for Quantum-Selected Configuration Interaction,” arXiv:2604.09756 (2026). [Mitsubishi Chemical Corporation — a challenge provider; N₂ active spaces to 32 qubits]"),
];
children.push(...refs);
children.push(new Paragraph({spacing:{before:160,after:40,line:240,lineRule:"auto"},children:[
  new TextRun({text:"AI-use disclosure. ",font:FONT,size:19,bold:true,italics:true}),
  new TextRun({text:"Generative AI assisted code and writing (per the challenge's stated permission for code support and writing); all technical contributions, formulations, and results are the team's own — every judged claim is pre-registered with frozen protocols and thresholds and traces to a committed script + evidence file, with all governance decisions carrying operator sign-offs in the git history.",font:FONT,size:19,italics:true})]}));

const doc=new Document({
  styles:{default:{document:{run:{font:FONT,size:SZ}}}},
  sections:[{properties:{page:{size:{width:12240,height:15840},margin:{top:1080,right:720,bottom:1080,left:720}}},children}]
});
Packer.toBuffer(doc).then(b=>{fs.writeFileSync("EIGENNEXUS_Phase3_Content.docx",b);console.log("Created EIGENNEXUS_Phase3_Content.docx:",b.length,"bytes");});
