// Phase 3 write-up builder (docx-js), mirroring build_phase2.js.
// Generates EIGENNEXUS_Phase3_Content.docx from the Phase 3 draft prose.
// [QBRAID-RUN] placeholders are styled (bold italic, dark red) so the GPU/QPU numbers
// owed are unmistakable and easy to find-and-replace once executed.
const { Document, Packer, Paragraph, TextRun, Table, TableRow, TableCell,
        AlignmentType, BorderStyle, WidthType, ShadingType, ImageRun } = require('docx');
const fs = require('fs');

const FONT="Times New Roman", SZ=22; // 11pt
const bd={style:BorderStyle.SINGLE,size:1,color:"888888"};
const borders={top:bd,bottom:bd,left:bd,right:bd};
const cw=9792;

function P(runs,opts={}){return new Paragraph({spacing:{after:opts.after??44,line:226,lineRule:"auto"},alignment:opts.align,...opts,children:Array.isArray(runs)?runs:[runs]});}
function T(t,o={}){return new TextRun({text:t,font:FONT,size:SZ,bold:o.b,italics:o.i});}
function Q(t){return new TextRun({text:t,font:FONT,size:SZ,bold:true,italics:true,color:"A52A2A"});} // [QBRAID-RUN] placeholder
function H(t){return new Paragraph({spacing:{before:64,after:32,line:226,lineRule:"auto"},children:[new TextRun({text:t,font:FONT,size:SZ,bold:true})]});}

function cell(text,w,{hdr=false,bold=false,align=AlignmentType.LEFT}={}){
  return new TableCell({borders,width:{size:w,type:WidthType.DXA},
    shading:{fill:hdr?"D5E8F0":"FFFFFF",type:ShadingType.CLEAR},
    margins:{top:40,bottom:40,left:90,right:90},
    children:[new Paragraph({alignment:align,spacing:{after:0,line:240,lineRule:"auto"},
      children:[new TextRun({text:text,font:FONT,size:21,bold:hdr||bold})]})]});
}
function row(cells,w,opts={}){return new TableRow({children:cells.map((c,i)=>cell(c,w[i],opts))});}

// Table 1: verified results (5a) — quantum vs classical, matched instances
const w1=[2000,1100,2900,2400,1392];
const tbl1=new Table({width:{size:9792,type:WidthType.DXA},columnWidths:w1,rows:[
  row(["System","Qubits","Quantum (GQE/QSCI)","Classical ref.","Notes"],w1,{hdr:true,align:AlignmentType.CENTER}),
  row(["H₂/H₄/H₆","4/8/12","0.000 / 0.009 / 0.297 mHa","FCI (exact)","two-stage GQE (UCCSD)"],w1,{align:AlignmentType.CENTER}),
  row(["H₆ GQE→QSCI","12","1.05 mHa (51→1.05, ~50×)","FCI","measured pipeline"],w1,{align:AlignmentType.CENTER}),
  row(["H₁₀/H₁₄","20/28","0.57 / 1.21 mHa","FCI / CCSD(T)","2,401 / 18,201 dets"],w1,{align:AlignmentType.CENTER}),
  row(["CrO ⁵Π / NiO ³Σ⁻","20","0.038 / 0.197 mHa","CASCI (exact)","open-shell multiref."],w1,{align:AlignmentType.CENTER}),
  row(["SnO / SnO₂","16/20","chem. acc. ≤0.6 (obs. 0.11–0.13 / 0.13–0.23)","FCI","EUV target; values version/run sensitive"],w1,{align:AlignmentType.CENTER}),
  row(["Noise (H₁₀)","20","≤3.3 mHa @ 30% corrupt (2×10⁶ shots)","—","noise-aware bonus"],w1,{align:AlignmentType.CENTER}),
]});

// Table 2: classical baseline & exact wall (5b) — timed, matched instances
const w2=[1700,1300,2400,2300,2092];
const tbl2=new Table({width:{size:9792,type:WidthType.DXA},columnWidths:w2,rows:[
  row(["System","Qubits","FCI (exact) wall-clock","CCSD(T) err vs FCI","CCSD(T) wall-clock"],w2,{hdr:true,align:AlignmentType.CENTER}),
  row(["H₆","12","0.08 s","0.026 mHa","0.09 s"],w2,{align:AlignmentType.CENTER}),
  row(["H₁₀","20","0.74 s","0.173 mHa","0.15 s"],w2,{align:AlignmentType.CENTER}),
  row(["H₁₂","24","5.02 s","0.282 mHa","0.17 s"],w2,{align:AlignmentType.CENTER}),
  row(["H₁₄","28","minutes","—","~0.2 s"],w2,{align:AlignmentType.CENTER}),
  row(["H₁₆+","32+","intractable (CPU)","—","—"],w2,{align:AlignmentType.CENTER}),
]});

const children=[
  new Paragraph({spacing:{after:30,line:240,lineRule:"auto"},alignment:AlignmentType.CENTER,
    children:[new TextRun({text:"MATGEN-Q: Scaling a Two-Stage Generative Quantum Eigensolver to 40 Qubits on NVIDIA CUDA-Q for EUV Photoresist Chemistry",font:FONT,size:24,bold:true})]}),
  new Paragraph({spacing:{after:80,line:240,lineRule:"auto"},alignment:AlignmentType.CENTER,
    children:[new TextRun({text:"Team EIGENNEXUS  —  Advanced Materials (Mitsubishi Chemical Group & AIST)  —  GIC 2026 Phase 3",font:FONT,size:21,italics:true})]}),

  H("1. Focus Area and Rationale"),
  P([T("Ground-state energy estimation governs reaction thermodynamics, redox behavior, and excited-state properties across materials chemistry, yet classical methods scale exponentially with electron correlation and the gold-standard CCSD(T) costs O(N⁷). The Generative Quantum Eigensolver (GQE; Nakaji et al. 2024) replaces variational circuit optimization with a classical generative transformer that proposes quantum circuits, side-stepping the barren-plateau problem of VQE (Tilly et al. 2022; a GQE property established by Nakaji et al. 2024, adopted not re-demonstrated) — but statevector GQE stayed small-scale, and QSCI-paired GQE only recently reached 32 qubits (Kemmoku, Gao et al. 2026). "),T("Scaling this generative approach to the ~40-qubit, industrially relevant regime — with executed, reproducible results — is the problem we address in Phase 3.",{b:true}),T(" Our primary, executed contribution is quantum-accurate energies for the exact chemistry where the classical gold standard fails — single-reference CCSD(T) collapses non-variationally below the exact energy as bonds break, a confidently-wrong result with no internal error signal — on open-shell, multireference transition-metal oxides (CrO, NiO) and EUV-relevant tin oxides (SnO, SnO₂) at 20 qubits, validated against exact diagonalization and third-party HamLib Hamiltonians. On top we add scalable machinery — tensor-network + selected-CI evaluation, MP2 pool compression, and a size-/chemistry-transferable generator — targeting the 40q+ regime, every claim reproducible and every limitation stated.")]),
  P([T("Our target is EUV semiconductor photoresist chemistry (tin-oxo clusters; Sn, Hf, Zr oxides), whose open-shell, multireference character breaks single-reference classical methods — the focus of an active quantum-simulation program by one of this challenge's providers (Kharazi et al., Xanadu & Mitsubishi Chemical, 2026). We quantify this directly (Figure 1, §5): as a real Cr–O bond stretches into the strongly-correlated regime, in-active-space CCSD(T) collapses non-variationally (error growing to ~140 mHa, frequently non-convergent) while the variational selected-CI/QSCI selector stays a rigorous, self-certifying bound within chemical accuracy throughout — a trustworthy quantum-accurate answer exactly where the classical gold standard is confidently wrong. The pipeline (AI proposes → classical screens → GQE/QSCI refines → Bayesian selects) generalizes to battery electrolytes, catalysts, and polymers central to Mitsubishi Chemical and AIST; in an $800B+ semiconductor industry, multi-fidelity screening economics (Fare et al., 2022) are the cost lever MATGEN-Q targets via quantum-accurate pre-selection.")]),
  P([T("Stakeholder relevance. ",{b:true}),T("For Mitsubishi Chemical: a quantum-accurate, self-certifying filter ahead of costly synthesis and lithographic testing, where single-reference classical methods misjudge strongly-correlated tin-oxo energetics; for AIST/G-QuAT: a scalable, reproducible GQE workflow on CUDA-Q extending the jointly-developed program past its size limits.")]),

  H("2. Target System and Data Modeling Strategy"),
  P([T("Scaling vehicle. ",{b:true}),T("The Hₙ chain series (n = 2…20; 4–40 qubits, STO-6G, Jordan–Wigner) — the canonical strong-correlation benchmark; one bond-length parameter tunes weak to strong correlation, stressing the simulation layer behind any scaling claim.")]),
  P([T("Target chemistry. ",{b:true}),T("The same QSCI engine reaches chemical accuracy on real materials chemistry: Sn-oxide active spaces (Sn ECP-CASCI, validated on H₄ to 0.0000 mHa) — SnO (16q) and SnO₂ (20q) to chemical accuracy (≤0.6 mHa asserted by reproduce.py; observed 0.11–0.13 / 0.13–0.23 across PySCF versions), and — to reach the genuine EUV motif rather than a diatomic — a bridged "),T("Sn–O–Sn tin-oxo fragment (Sn₂O₂ rhombus) to 0.41 mHa at 16q",{b:true}),T("; and genuine open-shell, multireference transition-metal oxides —"),T("CrO ⁵Π 0.038 mHa and NiO ³Σ⁻ 0.197 mHa at 20 qubits",{b:true}),T(". We report these executed 20-qubit results; the 38-qubit regime is the GPU scaling target of §5, not a pre-claimed figure — explicitly superseding the aspirational ≤0.08 mHa @38q of our Phase 2 draft, which we do not claim.")]),
  P([T("Data integrity. ",{b:true}),T("We adopt HamLib (Sawaya et al., Quantum 2024) and built a generation pipeline replicating its methodology (PySCF → OpenFermion → Jordan–Wigner, STO-6G). "),T("Validated against the published files: FCI reproduced to 0.00000 mHa (H₂–H₆), and at 28/32/40 qubits our Hamiltonians match HamLib exactly in term count (27,735 / 47,489 / 116,577) and to ~15 significant figures in coefficient magnitude",{b:true}),T(" (differing only by a spectrum-invariant orbital-phase convention) — third-party reproducible.")]),
  P([T("Accuracy anchors / classical references. ",{b:true}),T("FCI exactly (≤20q), CCSD(T) near equilibrium, and DMRG — verified to reproduce FCI to 0.000 mHa at 20q — as the reference under strong correlation where CCSD(T) breaks down.")]),

  H("3. GQE-Based Approach and Algorithmic Innovation"),
  P([T("MATGEN-Q uses a two-stage GQE. Stage 1 (generative structure discovery): ",{b:true}),T("a decoder-only GPT-style transformer, trained by sequence–energy matching (Nakaji et al.), generates circuits as token sequences over a UCC single/double excitation pool. "),T("Stage 2 (continuous refinement): ",{b:true}),T("adjoint-gradient angle optimization converges to chemical accuracy. Four innovations make it scalable:")]),
  P([T("(1) Tensor-network (MPS) simulation — the GPU scaling enabler, bond-dimension argument now demonstrated on CPU. ",{b:true}),T("CUDA-Q's tensornet-mps memory scales with entanglement, not 2ⁿ; we verify the enabling claim with block2 DMRG: "),T("the bond dimension χ for chemical accuracy grows only modestly with size (χ≈50/100/400 at 20/28/40 qubits), entanglement area-law-bounded near equilibrium (Sₘₐₓ 0.39) rising into strong correlation (Sₘₐₓ 4.43)",{b:true}),T(". So at 40q, χ≈400 puts the MPS footprint (~n·χ²·d, megabytes) far below the ~16 TB exact statevector. The 20q/28q GPU runs are executed to chemical accuracy (§5); the full 40q tensornet-mps run remains the primary owed deliverable, de-risked by the measured χ target and the ≈5× faster growth engine.")],{after:30}),
  P([T("(2) QSCI energy evaluation — accuracy and noise-aware. ",{b:true}),T("Quantum-Selected Configuration Interaction (Kanno et al. 2023): dominant configurations are sampled from the generated circuit and H is classically diagonalized in that subspace — intrinsically noise-robust (the device defines only the subspace; at 20q with 2×10⁶ shots the energy degrades gracefully to ≤3.3 mHa even with 30% of measurements corrupted; and executed through CUDA-Q's density-matrix backend with a physical depolarizing channel, QSCI on H₄ holds chemical accuracy up to 5% per-gate noise — a selection-principle robustness check on a small determinant space, not a hardware forecast).")],{after:30}),
  P([T("(3) Operator-pool compression — efficiency (demonstrated). ",{b:true}),T("Ranking the O(N⁴) double-excitation pool by active-space MP2 amplitude and keeping the top fraction shrinks the transformer vocabulary with negligible accuracy loss, where random pruning collapses. Deterministic CI-subspace test (CO/N₂/SiO, 12q): "),T("N₂ retains full-pool accuracy (2.26 mHa) keeping only 25% of doubles (vocabulary 1170→430) vs 50.4 mHa for random pruning at the same size (~22×)",{b:true}),T("; CO holds 3.7 mHa at 40% kept vs 29.7 mHa random.")],{after:30}),
  P([T("(4) Distributed hybrid workflow. ",{b:true}),T("Detailed in §4.")],{after:30}),
  P([T("Transfer learning — a generative prior that transfers across system size and chemistry. ",{b:true}),T("Using a canonical, frontier-relative tokenization (each excitation encoded as occupied-depth-below-HOMO and virtual-height-above-LUMO, independent of qubit count), a small system's token vocabulary is a provable subset of a larger one (H₆/12q ⊂ H₈/16q ⊂ H₁₀/20q). One GPT-QE generator trained only on H₄+H₆ (8q+12q) is deployed zero-shot across 16→56 qubits. "),T("The robust signals are statistical: ~3.6× tighter selection spread than random (≈1.4 vs ≈5.1 mHa across-seed SD) and 43/48 size×seed paired wins at 8 seeds (binomial p<0.0001)",{b:true}),T(" — reliable selection versus a lottery. The per-size mean advantage is positive at every size and stays significant (7/8 wins) through 56q, narrowing only in magnitude (+7.1→+3.9 mHa, 16→56q). That the learned policy captures real chemistry is corroborated by interpretability: trained on energy alone, it recovers the MP2 double-excitation amplitude hierarchy (Spearman ρ=0.31, p<0.002; 4 of its top-8 doubles are MP2's). This is the"),T("train-small, deploy-large",{i:true}),T(" idea: GQE training is CPU-bound near ~16 qubits, so transferring a small-trained generator toward the 40q+ target — instead of training at scale — speaks directly to the scalability criterion. The enabler is a determinant-space evaluation (each excitation maps by bitmask to a determinant, diagonalized via Slater-Condon, validated to 0.0000 mHa against Jordan–Wigner), needing no 2ⁿ statevector, so 56q runs on CPU — a "),T("selected-CI proxy",{i:true}),T(" for circuit-sampled QSCI, relative at a small fixed budget (K=96), not absolute chemical accuracy. ")]),
  P([T("Cross-chemistry transfer (honest, partial). ",{b:true}),T("The same H-chain-trained generator, deployed to oxide active spaces, beats random clearly on 3 of 6 targets (CO-12q/SiO/CO-20q), ties on BeO, loses on SnO (heavy-element ECP chemistry too dissimilar). Target-specific MP2 is the strongest selector on every target: cross-size transfer is robust, cross-chemistry works only when the target resembles training — a zero-cost prior, not a universal one. A same-size conditional-GQE variant (cf. Minami, Nakaji et al. 2025) gave only a within-noise gain, also a reported negative.")]),


  H("4. Hybrid Architecture"),
  P([T("The classical transformer trains on GPU (PyTorch); circuit evaluations are dispatched across GPUs via CUDA-Q's mqpu in an asynchronous generate→evaluate→update loop — quantum resources do state preparation and energy estimation (MPS/QSCI), classical resources do generation, optimization, and active-space selection. "),T("We validate this execution path on CUDA-Q itself: the UCCSD/QSCI pipeline runs through CUDA-Q's qpp-cpu backend and reproduces exact FCI on H₄ (VQE within 0.02 mHa via cudaq.observe; QSCI within chemical accuracy via cudaq.sample), confirming the generated circuits compile and sample through the SDK — and the full QPU submission chain (export→submit→decode→QSCI) is executed end-to-end through the qBraid cloud runtime on its free simulator tier (+2.0 mHa vs FCI, job IDs committed); the 20q and 28q GPU runs are now executed on NVIDIA hardware through qBraid (§5), the 40q tensornet-mps run and real QPU silicon owed.",{b:true})]),

  H("5. Phase 3 Execution and Results"),
  P([T("Verified results (CPU).",{b:true}),T(" One command ("),T("reproduce.py",{i:true}),T(") runs 26 automated checks (17 re-executions + 9 committed-artifact audits incl. the pre-registration SHA-256, the AQT trapped-ion decode, and a cost audit that re-derives the program spend from published pricing × committed shot/uptime configs): "),T("26/26 PASS",{b:true}),T("; every value traces to a committed result file (Table 1).")],{after:50}),
  tbl1,
  new Paragraph({spacing:{before:30,after:50,line:240,lineRule:"auto"},children:[new TextRun({text:"Table 1. Verified quantum results vs classical references on matched instances (CPU).",font:FONT,size:19,italics:true})]}),
  P([T("Classical baseline and the exact wall (matched instances, timed). ",{b:true}),T("On identical STO-6G Hₙ geometries, classical FCI wall-clock grows steeply (~6.8× from 20→24 qubits, 0.74 s → 5.02 s on a single CPU thread) and is intractable by 32q on CPU; CCSD(T) stays cheap but its error climbs with correlation and breaks down under strong correlation (at H₂₄/48q, classical DMRG is itself 6.83 mHa off CCSD(T)). Exact statevector needs ~16 TB at 40q vs ~0.2 GB for the MPS tier (measured χ=400), and ~10⁶ QSCI determinants vs ~3×10¹⁰ for full CI — the memory and determinant walls the MPS + QSCI tiers remove (Table 2; quantified in results/crossover).")],{after:50}),
  tbl2,
  new Paragraph({spacing:{before:30,after:50,line:240,lineRule:"auto"},children:[new TextRun({text:"Table 2. Classical reference cost on the Hₙ ladder (single-thread CPU; wall-clocks machine-dependent, reproduced in classical_baselines_evidence.json — the steep growth and exact-method wall, not absolute seconds, are the claim; H₁₄+ rows qualitative).",font:FONT,size:19,italics:true})]}),
  P([T("Executed on qBraid GPU (real hardware runs, corrected incremental engine). ",{b:true}),T("Two at-scale runs executed on NVIDIA GPU through qBraid, each judged against a reference committed before access (git-timestamped preregistration): "),
     T("20q H₁₀ (cuStateVec) ",{b:true}),T("reproduces full CI to "),T("+0.000 mHa",{b:true}),T(" at 0.44 GB device memory — an exact GPU-execution anchor; "),
     T("28q H₁₄ (cuStateVec) ",{b:true}),T("— a device-sampled QSCI grown to 64,212 determinants — reaches "),T("+0.395 mHa vs block2 DMRG(χ=400)",{b:true}),T(" at 2.82 GB device memory, chemical accuracy above the 20q scale on hardware. Both meet their pre-registered energy (P1) and device-memory (P3) criteria. "),
     T("40q H₂₀ (primary criterion): ",{b:true}),T("the fast incremental engine drives the QSCI error "),T("monotonically 8.9→3.2→1.226 mHa as the budget grows 30k→150k→450,257 determinants",{b:true}),T(" (~(dets)⁻⁰·⁷), meeting the pre-registered P1 chemical-accuracy criterion vs the committed DMRG(χ=400) reference (P2 determinant-band also met, ahead of its ~10⁶-det estimate); the run stopped at iter-3 by a disk ceiling (disclosed in-evidence — variational, so an early stop can only worsen a pass, never manufacture one; attempt-1's old engine stalled at 6k/+14.8 mHa). Absolute accuracy (vs a stricter χ=800 reference, +2.19 mHa) is E3/E6's job, below. The subspace is MP2-seeded (the tensornet-mps sampler's fixed MPS-contraction cost is impractical at 40q; growth is seed-independent, device sampler proven exact at 20q/28q). "),
     T("CrO near-38q — we corrected the classical reference (Figure 2): ",{b:true}),T("QSCI on CrO CAS(18,19)=38q converged "),T("−3.784 mHa BELOW the same-CAS DMRG(χ=400) reference",{b:true}),T(" (529,392 determinants, 19.1 h; reference committed before access). Both are "),T("variational upper bounds on the identical Hamiltonian",{b:true}),T(", so the lower energy is strictly the more accurate one, and the pre-registered χ-escalation confirms it (Figure 2). This is the P4 criterion FAILING as-measured (|Δ|>1.6 mHa) — because it assumed DMRG(χ=400) was truth, and the result disproved that assumption. "),
     T("Real-QPU silicon (10–16q) — executed and decoded: ",{b:true}),T("the 3-job pooled protocol ran end-to-end through qBraid (qir-sv simulator tier: +2.0 mHa vs FCI, PASS, job IDs committed), and the trapped-ion flight (AQT ibex-q1, 2,000 shots/job, SHA-pinned exports) decoded 2026-07-20 — number-conserving post-selection kept 28.6% / 25.1% of shots, the device-sampled determinants give +20.4 / +11.1 mHa, and device-seeded QSCI growth recovers exact FCI (0.000 mHa) — genuine 12-qubit trapped-ion samples driving the same QSCI machinery as the 40q runs.")]),
  P([T("Determinant-budget sweep. ",{b:true}),T("The generator beats random at every budget up to K=96 (at K=128 they converge, random marginally ahead); target-specific MP2 remains the strongest selector, so the transferred prior is a "),T("zero-cost head start, not a winner",{i:true}),T(".")]),
  P([T("What the results establish. ",{b:true}),T("Three things, demonstrated not asserted: (i) correctness — the pipeline reproduces the FCI/CASCI reference to chemical accuracy on every instance we can run, including multireference oxides and EUV Sn-oxides; (ii) scalability — QSCI reaches chemical accuracy on a vanishing fraction of the CI space (3.8% at 20q, 0.15% at 28q); (iii) transferable structure (§3). The honest boundary is stated in §7.")]),

  P([T("Where it matters most: trust under strong correlation. ",{b:true}),T("Stretching H₁₀ (20q) to dissociation drives genuine multireference character (Hartree–Fock weight in the exact wavefunction falls 0.93→0.06), and the classical gold standard fails qualitatively: CCSD(T) collapses "),T("non-variationally",{i:true}),T(" to 217 mHa BELOW the exact FCI energy at R=2.4 Å — a confidently wrong, unphysical answer. The determinant-subspace method (the QSCI principle, here via iterative selected-CI) instead "),T("reaches chemical accuracy with only ~500 determinants",{b:true}),T(" at every geometry across the dissociation, a rigorous variational bound systematically convergent to the exact answer. "),T("Critically this is not a hydrogen-chain artifact: on a real Cr–O bond stretch (CrO ⁵Π, CAS(10,10)=20q), in-active-space CCSD(T) develops large, frequently non-convergent errors (tens to ~140 mHa vs exact CASCI) as the dominant-determinant weight falls 0.87→0.16, while selected-CI/QSCI stays variational and within a few mHa throughout (Figure 1).",{b:true}),T(" And we certify the error rather than assert it: an Epstein–Nesbet PT2 correction tightens the rigorous variational upper bound toward FCI — "),T("E_var+PT2 is a second-order estimate (not a bound) that at our budgets converges to FCI from above",{b:true}),T(": near equilibrium the CIPSI extrapolation reproduces FCI to ~4 mHa (R²=0.999), and even at the strongest correlation (R=2.4 Å, 468 determinants) E_var+PT2 sits +10.9 mHa above FCI with the shrinking E_var↔E_var+PT2 gap as the convergence certificate — while CCSD(T) sits 217 mHa BELOW FCI with no error signal at all. (Selected-CI here is classical on CPU; QSCI is its device-driven instantiation — realized on GPU hardware by the 28q run.)",{}),T("R&D value: ",{b:true}),T("a confidently-wrong classical energy — a non-variational binding energy that sits below the exact answer with no error flag — commits multi-month synthesis spend to a false lead, the dominant hidden cost of discovery, which a self-certifying variational selector that stays correct where CCSD(T) silently fails directly reduces.")]),
  new Paragraph({keepNext:true,spacing:{before:40,after:8,line:240,lineRule:"auto"},alignment:AlignmentType.CENTER,
    children:[new ImageRun({type:"png",data:fs.readFileSync("../results/cro_dissociation.png"),transformation:{width:158,height:101}})]}),
  new Paragraph({spacing:{before:0,after:60,line:240,lineRule:"auto"},alignment:AlignmentType.CENTER,
    children:[new TextRun({text:"Figure 1. Trust on a real oxide. As the CrO ⁵Π bond stretches (left→right), in-active-space CCSD(T) becomes erratic and frequently non-convergent (open markers), a few to ~140 mHa vs exact CASCI, while selected-CI/QSCI stays a variational bound within chemical accuracy (≤2.8 mHa). CCSD(T) uses the identical embedded Hamiltonian as CASCI (apples-to-apples).",font:FONT,size:18,italics:true})]}),
  new Paragraph({keepNext:true,spacing:{before:40,after:8,line:240,lineRule:"auto"},alignment:AlignmentType.CENTER,
    children:[new ImageRun({type:"png",data:fs.readFileSync("../results/chi_ladder_correction.png"),transformation:{width:140,height:81}})]}),
  new Paragraph({spacing:{before:0,after:60,line:240,lineRule:"auto"},alignment:AlignmentType.CENTER,
    children:[new TextRun({text:"Figure 2. Correcting the classical reference at 38q. Escalating the bond dimension walks DMRG down toward our QSCI energy (+3.78 → +1.06 → +0.36 mHa at χ=400/800/1200), never crossing it. Both bound the same CAS(18,19) Hamiltonian from above, so the lower energy is strictly more accurate: the committed χ=400 reference carried a silent truncation error.",font:FONT,size:18,italics:true})]}),
  P([T("Frozen extension campaign (E2–E6; pre-registered before access, executed 2026-07-23/24, reported as measured). ",{b:true}),T("The protocols were git-timestamped (preregistration_v2.json + _e67_supplementary.json) before access; reported exactly as measured — pass, fail, or resource-DNF. "),
     T("E4 — a second reference correction, on the real EUV motif: ",{b:true}),T("QSCI on the committed Sn₂O₂ rhombus (CAS(18,19)=38q) converged "),T("−0.399 mHa BELOW the same-CAS DMRG(χ=400) reference",{b:true}),T(" (524,764 dets, 7.4 h; reference committed pre-run) — the correction reproduced on the actual tin-oxo chemistry. "),
     T("EUV-motif trust curve: ",{b:true}),T("stretching the Sn₂O₂ Sn–O bridge 2.05→3.28 Å (the strongly-correlated cleavage regime), in-active-space CCSD(T) error grows "),T("0.14→5.49 mHa (~40×)",{b:true}),T(" while the identical selected-CI/QSCI stays variational (≤0.48 mHa everywhere) and the dominant-determinant weight collapses 0.95→0.53 — Figure 1's trust story on the real motif under cleavage. "),
     T("E3 — the 40q absolute-certification protocol (terminal at it5): ",{b:true}),T("growth-to-PT2-certificate on H₂₀ 40q, bucket-parallel Epstein–Nesbet (bit-identical to serial); ended by an external pod kill during it6 growth (disclosed, not a convergence failure). At it5: "),T("E_var +0.185 mHa vs χ=400 (ii MET), 750,257 dets (iii MET)",{b:true}),T(", |PT2| a clean converging trace 84→4.6→2.6→2.0→1.57→1.31 mHa; the |PT2|≤0.5 point (i, ~it10–11) unreached, as-measured. "),
     T("E2 — resource-DNF, disclosed as an operational record (not the E2 result): ",{b:true}),T("the device-seeded 40q run (committed 102-det seed) needs ≥128 GiB and was OOM-killed by the cgroup at iter-3 cap-fill (peak 133.5 GB, 97%; two deterministic attempts). E4 completed on the same box at 59.7 GB — +2 qubits double the footprint. An honest hardware ceiling, no tuning. "),
     T("E5 — the least-grounded frontier (44q), non-converged and reported as such: ",{b:true}),T("H₂₂ 44q growth against a re-frozen χ=1200 judge, terminated early to protect E3's runway; committed trajectory +125→+8.7→+5.2→+4.0 mHa (decelerating), not reaching the ≤1.6 mHa threshold before the abort gate — the pre-registered expected outcome, no threshold moved and frozen parameters untouched. "),
     T("E6 — an independent absolute-accuracy anchor (supplementary, pre-registered): ",{b:true}),T("high-χ DMRG (χ=400→2400) on the identical H₂₀/40q Hamiltonian, extrapolated on discarded weight to "),T("FCI(40q) = −10.293599 ± 0.022 mHa (R²=0.997)",{b:true}),T(" — placing E3's committed it5 variational energy "),T("+1.59 mHa from the near-exact limit — at the 1 kcal/mol chemical-accuracy edge, jackknife-robust to ±0.05 mHa",{b:true}),T(" (leave-one-out spans +1.55→+1.61 mHa; e6_jackknife.py) — by a classical route independent of the killed PT2 certificate.")]),
  P([T("Proxy validated against real measurement; cost scaling. ",{b:true}),T("We confirm the determinant-space proxy tracks the real circuit-sampled pipeline by executing measured QSCI (qml.sample, 3,000 shots × 160 circuits) at 16q and 20q — measured matches proxy (16q: 28.1 vs 26.6; 20q: 50.4 vs 49.3 mHa), extending the sampled pipeline past 12q (at this shot budget diffuse random sampling edges out the generator — a low-shot coverage effect, not a quality reversal). Determinants for chemical accuracy grow ~1.38× per qubit vs 2.0× for FCI (log R²=0.99) — vanishing but still exponential; we do not claim polynomial scaling.")]),

  H("6. Platform Use and Resourcing"),
  P([T("We use "),T("NVIDIA H100/A100 (80 GB)",{b:true}),T(" with CUDA-Q: tensornet-mps for the 24–40q tier, cuStateVec for exact validation to ~32q; multi-GPU (NVLink) enables distributed evaluation and the >40q bonus; QPU for 10–16q validation. The ~16 TB exact statevector at 40q collapses onto one 80 GB GPU via CUDA-Q MPS (~200× reduction) — what makes the 40-qubit tier reachable.")]),
  P([T("Resource estimate. ",{b:true}),T("With pool compression a length-8 UCC circuit is shallow (≤2-qubit gates), within MPS reach near equilibrium; QSCI needs ~10³–10⁴ shots/circuit. We estimate ~1–2 weeks single-GPU wall-clock for the full 24→40q sweep plus oxide runs. Measured: 20q 191 s, 28q 2,386 s total — GPU sampling 1–32 s, the rest classical determinant growth (the wall at scale, cut ≈5× by the incremental engine).")]),

  H("7. Limitations and Honest Scope"),
  P([T("We state where the approach does and does not yet provide benefit. (i) ",{}),T("Measurement vs proxy: ",{b:true}),T("the GQE→QSCI loop is measured at 12q and executed with real GPU sampling at 20q/28q (§5); larger QSCI numbers use a hardware-independent determinant-space proxy. (ii) ",{}),T("No classical-beating claim yet: ",{b:true}),T("at ≤28q classical FCI/DMRG already solve these instances, so we show correctness and favourable scaling, not a head-to-head speed advantage; that regime is 40q+ strong correlation where DMRG bond dimension explodes. (iii) ",{}),T("40q absolute certification: ",{b:true}),T("the flagship meets its pre-registered relative criterion; the frozen E3 certificate reached a terminal it5 (external pod kill during it6 growth), prediction ii met, the |PT2|≤0.5 absolute point unreached — reported as-measured (§5e). (iv) ",{}),T("Transfer scope: ",{b:true}),T("cross-size transfer is significant at 8 seeds (43/48 wins, p<0.0001), the advantage narrowing in magnitude but positive through 56q; cross-chemistry wins 3 of 6 oxides (BeO a tie), fails on SnO; target-specific MP2 beats the transferred prior — a zero-cost prior, not a universal or MP2-beating one.")]),

  H("8. Conclusion and Reproducibility"),
  P([T("MATGEN-Q contributes on four axes. "),
     T("AI: ",{b:true}),T("a classical generative transformer designs the circuits and "),T("transfers",{i:true}),T(" — trained at 8q+12q, deployed zero-shot to 56q (43/48 wins, p<0.0001). "),
     T("Quantum: ",{b:true}),T("paired with QSCI and executed on hardware — 40q chemically accurate vs its frozen reference, 20q/28q GPU, trapped-ion silicon, and two 38q runs that "),T("correct",{i:true}),T(" their DMRG references. "),
     T("Business: ",{b:true}),T("a pre-synthesis trust gate — where CCSD(T) is "),T("confidently wrong",{i:true}),T(", QSCI is variational and self-certifying, so synthesis spend is not committed to a false lead. "),
     T("Scientific: ",{b:true}),T("every judged claim pre-registered and reported as measured, including a resource-DNF, a non-convergence, and two claims we "),T("withdrew",{i:true}),T("; one command ("),T("reproduce.py",{i:true}),T(", 26/26) re-runs every headline result.")]),

  new Paragraph({spacing:{before:120,after:40,line:240,lineRule:"auto"},pageBreakBefore:true,children:[new TextRun({text:"References",font:FONT,size:SZ,bold:true})]}),
];
function refP(n,txt){return new Paragraph({spacing:{after:30,line:240,lineRule:"auto"},indent:{left:360,hanging:360},children:[new TextRun({text:"["+n+"] ",font:FONT,size:20,bold:true}),new TextRun({text:txt,font:FONT,size:20})]});}
const refs=[
 refP(1,"K. Nakaji, et al. “The generative quantum eigensolver (GQE) and its application for ground state search.” arXiv:2401.09253 (2024). [AIST]"),
 refP(2,"N. P. D. Sawaya, et al. “HamLib: A library of Hamiltonians for benchmarking quantum algorithms and hardware.” Quantum 8, 1559 (2024)."),
 refP(3,"S. Minami, K. Nakaji, et al. “Generative quantum combinatorial optimization … conditional generative quantum eigensolver.” Digital Discovery 4(8) (2025)."),
 refP(4,"K. Kanno, et al. “Quantum-selected configuration interaction … subspaces selected by quantum computers.” arXiv:2302.11320 (2023)."),
 refP(5,"NVIDIA Corporation. CUDA-Q and cuQuantum SDK (cuStateVec, tensornet / tensornet-mps backends)."),
 refP(6,"J. Tilly, et al. “The Variational Quantum Eigensolver: A review of methods and best practices.” Physics Reports 986 (2022)."),
 refP(7,"C. Fare, et al. “A multi-fidelity machine learning approach to high-throughput materials screening.” npj Computational Materials 8, 257 (2022)."),
 refP(8,"T. D. Kharazi, et al. “Quantum Simulations for Extreme Ultraviolet Photolithography.” arXiv:2602.20234 (2026). [Xanadu & Mitsubishi Chemical]"),
 refP(9,"R. Kemmoku, Q. Gao, S. Kanno, et al. “Generative Circuit Design for Quantum-Selected Configuration Interaction.” arXiv:2604.09756 (2026). [Mitsubishi Chemical]"),
];
children.push(...refs);
children.push(new Paragraph({spacing:{before:160,after:40,line:240,lineRule:"auto"},children:[
  new TextRun({text:"AI-use disclosure. ",font:FONT,size:19,bold:true,italics:true}),
  new TextRun({text:"Generative AI assisted code and writing (per the challenge's stated permission for code support and writing); all technical contributions, formulations, and results are the team's own — every judged claim is pre-registered with frozen protocols and thresholds and traces to a committed script + evidence file, with all governance decisions carrying operator sign-offs in the git history.",font:FONT,size:19,italics:true})]}));

const doc=new Document({
  styles:{default:{document:{run:{font:FONT,size:SZ}}}},
  sections:[{properties:{page:{size:{width:12240,height:15840},margin:{top:1224,right:1224,bottom:1224,left:1224}}},children}]
});
Packer.toBuffer(doc).then(b=>{fs.writeFileSync("EIGENNEXUS_Phase3_Content.docx",b);console.log("Created EIGENNEXUS_Phase3_Content.docx:",b.length,"bytes");});
