// Phase 3 write-up builder (docx-js), mirroring build_phase2.js.
// Generates EIGENNEXUS_Phase3_Content.docx from the Phase 3 draft prose.
// [QBRAID-RUN] placeholders are styled (bold italic, dark red) so the GPU/QPU numbers
// owed are unmistakable and easy to find-and-replace once executed.
const { Document, Packer, Paragraph, TextRun, Table, TableRow, TableCell,
        AlignmentType, BorderStyle, WidthType, ShadingType, ImageRun } = require('docx');
const fs = require('fs');

const FONT="Times New Roman", SZ=22; // 11pt
const bd={style:BorderStyle.SINGLE,size:1,color:"888888"};
const borders={top:bd,bottom:bd,left:bd,right:bd};
const cw=9792;

function P(runs,opts={}){return new Paragraph({spacing:{after:opts.after??60,line:240,lineRule:"auto"},alignment:opts.align,...opts,children:Array.isArray(runs)?runs:[runs]});}
function T(t,o={}){return new TextRun({text:t,font:FONT,size:SZ,bold:o.b,italics:o.i});}
function Q(t){return new TextRun({text:t,font:FONT,size:SZ,bold:true,italics:true,color:"A52A2A"});} // [QBRAID-RUN] placeholder
function H(t){return new Paragraph({spacing:{before:90,after:40,line:240,lineRule:"auto"},children:[new TextRun({text:t,font:FONT,size:SZ,bold:true})]});}

function cell(text,w,{hdr=false,bold=false,align=AlignmentType.LEFT}={}){
  return new TableCell({borders,width:{size:w,type:WidthType.DXA},
    shading:{fill:hdr?"D5E8F0":"FFFFFF",type:ShadingType.CLEAR},
    margins:{top:40,bottom:40,left:90,right:90},
    children:[new Paragraph({alignment:align,spacing:{after:0,line:240,lineRule:"auto"},
      children:[new TextRun({text:text,font:FONT,size:21,bold:hdr||bold})]})]});
}
function row(cells,w,opts={}){return new TableRow({children:cells.map((c,i)=>cell(c,w[i],opts))});}

// Table 1: verified results (5a) — quantum vs classical, matched instances
const w1=[2000,1100,2900,2400,1392];
const tbl1=new Table({width:{size:9792,type:WidthType.DXA},columnWidths:w1,rows:[
  row(["System","Qubits","Quantum (GQE/QSCI)","Classical ref.","Notes"],w1,{hdr:true,align:AlignmentType.CENTER}),
  row(["H₂/H₄/H₆","4/8/12","0.000 / 0.009 / 0.297 mHa","FCI (exact)","two-stage GQE (UCCSD)"],w1,{align:AlignmentType.CENTER}),
  row(["H₆ GQE→QSCI","12","1.05 mHa (51→1.05, ~50×)","FCI","measured pipeline"],w1,{align:AlignmentType.CENTER}),
  row(["H₁₀/H₁₄","20/28","0.57 / 1.21 mHa","FCI / CCSD(T)","2,401 / 18,201 dets"],w1,{align:AlignmentType.CENTER}),
  row(["CrO ⁵Π / NiO ³Σ⁻","20","0.038 / 0.197 mHa","CASCI (exact)","open-shell multiref."],w1,{align:AlignmentType.CENTER}),
  row(["SnO / SnO₂","16/20","≤0.5 / 0.23 mHa (chem. acc.)","FCI","EUV target; SnO value PySCF-version sensitive"],w1,{align:AlignmentType.CENTER}),
  row(["Noise (H₁₀)","20","≤3.3 mHa @ 30% corrupt (2×10⁶ shots)","—","noise-aware bonus"],w1,{align:AlignmentType.CENTER}),
]});

// Table 2: classical baseline & exact wall (5b) — timed, matched instances
const w2=[1700,1300,2400,2300,2092];
const tbl2=new Table({width:{size:9792,type:WidthType.DXA},columnWidths:w2,rows:[
  row(["System","Qubits","FCI (exact) wall-clock","CCSD(T) err vs FCI","CCSD(T) wall-clock"],w2,{hdr:true,align:AlignmentType.CENTER}),
  row(["H₆","12","0.04 s","0.026 mHa","0.08 s"],w2,{align:AlignmentType.CENTER}),
  row(["H₁₀","20","0.33 s","0.173 mHa","0.09 s"],w2,{align:AlignmentType.CENTER}),
  row(["H₁₂","24","7.81 s","0.282 mHa","0.14 s"],w2,{align:AlignmentType.CENTER}),
  row(["H₁₄","28","minutes","—","~0.2 s"],w2,{align:AlignmentType.CENTER}),
  row(["H₁₆+","32+","intractable (CPU)","—","—"],w2,{align:AlignmentType.CENTER}),
]});

const children=[
  new Paragraph({spacing:{after:30,line:240,lineRule:"auto"},alignment:AlignmentType.CENTER,
    children:[new TextRun({text:"MATGEN-Q: Scaling a Two-Stage Generative Quantum Eigensolver to 40 Qubits on NVIDIA CUDA-Q for EUV Photoresist Chemistry",font:FONT,size:24,bold:true})]}),
  new Paragraph({spacing:{after:80,line:240,lineRule:"auto"},alignment:AlignmentType.CENTER,
    children:[new TextRun({text:"Team EIGENNEXUS  —  Advanced Materials (Mitsubishi Chemical Group & AIST)  —  GIC 2026 Phase 3",font:FONT,size:21,italics:true})]}),

  H("1. Focus Area and Rationale"),
  P([T("Ground-state energy estimation governs reaction thermodynamics, redox behavior, and excited-state properties across materials chemistry, yet classical methods scale exponentially with electron correlation and the gold-standard CCSD(T) costs O(N⁷). The Generative Quantum Eigensolver (GQE; Nakaji et al. 2024, with AIST) replaces variational circuit optimization with a classical generative transformer that proposes quantum circuits, side-stepping the barren-plateau problem that afflicts variational optimization (a property of GQE established by Nakaji et al. 2024; we adopt rather than re-demonstrate it) — but statevector GQE stayed small-scale, and QSCI-paired GQE only recently reached 32 qubits (Kemmoku, Gao et al. 2026). "),T("Scaling this generative approach to the ~40-qubit, industrially relevant regime — with executed, reproducible results — is the problem we address in Phase 3.",{b:true}),T(" Our primary, executed contribution is quantum-accurate energies for the exact chemistry where BOTH classical pillars fail — DFT's spin-state ordering flips sign across functionals (CrO splitting spans 1.9 eV) and single-reference CCSD(T) collapses non-variationally below the exact energy as bonds break — on open-shell, multireference transition-metal oxides (CrO, NiO) and EUV-relevant tin oxides (SnO, SnO₂) at 20 qubits, validated against exact diagonalization and third-party HamLib Hamiltonians. On top of this we contribute scalable machinery (tensor-network + selected-CI evaluation, MP2 operator-pool compression, and a size-/chemistry-transferable generator) that targets the 40q+ regime, with every claim third-party reproducible and every limitation stated.")]),
  P([T("Our target is EUV semiconductor photoresist chemistry (tin-oxo clusters; Sn, Hf, Zr oxides), whose open-shell, multi-reference character is where DFT's functional-dependent errors make candidate rankings unreliable, and which is the focus of an active quantum-simulation program by one of this challenge's providers (Kharazi et al., Xanadu & Mitsubishi Chemical, 2026). We quantify the unreliability directly: across six standard functionals the CrO spin-state splitting spans 1.9 eV — PBE0 places the quintet 1.84 eV below the triplet while B3LYP inverts the order (−0.08 eV) — and even the milder NiO gap varies 0.11 eV, against a chemical-accuracy target of 0.044 eV. A single quantum-accurate number removes this functional-choice band. The MATGEN-Q pipeline — AI proposes candidate metal-oxide molecules → DFT filters → GQE refines with quantum accuracy → Bayesian optimization selects the next candidate — generalizes beyond photoresists to battery electrolytes, catalysts, and functional polymers central to Mitsubishi Chemical's portfolio and AIST's computational-materials mission. EUV photoresists grow at ~20% CAGR within an $800B+ semiconductor industry, and multi-fidelity Bayesian screening has shown up to 3× cost reduction (Fare et al., 2022) — acceleration MATGEN-Q targets through quantum-accurate pre-selection.")]),
  P([T("Stakeholder relevance. ",{b:true}),T("For Mitsubishi Chemical the value is a quantum-accurate filter ahead of expensive synthesis and lithographic testing, where DFT mis-ranks tin-oxo redox/bond-cleavage energetics; for AIST/G-QuAT it is a scalable, reproducible GQE workflow on NVIDIA CUDA-Q that extends the jointly-developed program past its size limits and composes with its excited-state work into one materials-informatics loop.")]),

  H("2. Target System and Data Modeling Strategy"),
  P([T("Scaling vehicle. ",{b:true}),T("The linear hydrogen-chain series Hₙ (n = 2…20; 4–40 qubits, STO-6G, Jordan–Wigner) — the canonical strong-correlation benchmark; a single bond-length parameter tunes weak (area-law) to strong (volume-law) correlation, directly stressing the simulation layer that underpins any scaling claim.")]),
  P([T("Target chemistry. ",{b:true}),T("The same QSCI engine reaches chemical accuracy on real materials chemistry: Sn-oxide active spaces (Sn ECP-CASCI, validated on H₄ to 0.0000 mHa) — SnO chemical accuracy (≤0.5 mHa, 16q; exact value PySCF-version sensitive), SnO₂ 0.23 mHa (20q) — and genuine open-shell, multireference transition-metal oxides —"),T("CrO ⁵Π 0.038 mHa and NiO ³Σ⁻ 0.197 mHa at 20 qubits",{b:true}),T(". We report these executed 20-qubit results; the 38-qubit regime is the GPU scaling target of §5, not a pre-claimed figure.")]),
  P([T("Data integrity. ",{b:true}),T("We adopt HamLib (Sawaya et al., Quantum 2024) and built a generation pipeline replicating its methodology (PySCF → OpenFermion → Jordan–Wigner, STO-6G). "),T("Validated against the published files: FCI reproduced to 0.00000 mHa (H₂–H₆), and at 28/32/40 qubits our Hamiltonians match HamLib exactly in term count (27,735 / 47,489 / 116,577) and to ~15 significant figures in coefficient magnitude",{b:true}),T(" (differing only by a spectrum-invariant orbital-phase convention) — third-party reproducible.")]),
  P([T("Accuracy anchors / classical references. ",{b:true}),T("FCI exactly (≤20q), CCSD(T) near equilibrium, and DMRG — verified to reproduce FCI to 0.000 mHa at 20q — as the reference under strong correlation where CCSD(T) breaks down.")]),

  H("3. GQE-Based Approach and Algorithmic Innovation"),
  P([T("MATGEN-Q uses a two-stage GQE. Stage 1 (generative structure discovery): ",{b:true}),T("a decoder-only GPT-style transformer, trained by sequence–energy matching (Nakaji et al.), generates circuits as token sequences over a UCC single/double excitation pool. "),T("Stage 2 (continuous refinement): ",{b:true}),T("adjoint-gradient angle optimization converges to chemical accuracy. Four innovations make it scalable:")]),
  P([T("(1) Tensor-network (MPS) simulation — proposed GPU scaling enabler (not yet executed). ",{b:true}),T("CUDA-Q's tensornet-mps backend's memory scales with circuit entanglement rather than 2ⁿ, and near-equilibrium area-law structure bounds the bond dimension, so we propose it to carry exact circuit simulation past the ~32-qubit cuStateVec limit toward 40q+. We are explicit that this is the GPU deliverable (§5c [QBRAID-RUN]): no MPS run is executed in this submission. Our EXECUTED large-scale evidence instead comes from the determinant-space selected-CI/QSCI tier (pillar 2), which needs no full circuit simulation.")],{after:30}),
  P([T("(2) QSCI energy evaluation — accuracy and noise-aware. ",{b:true}),T("Quantum-Selected Configuration Interaction (Kanno et al. 2023): dominant configurations are sampled from the generated circuit and H is classically diagonalized in that subspace — intrinsically noise-robust (the device defines only the subspace; at 20q with 2×10⁶ shots the energy degrades gracefully to ≤3.3 mHa even with 30% of measurements corrupted).")],{after:30}),
  P([T("(3) Operator-pool compression — efficiency (demonstrated). ",{b:true}),T("Ranking the O(N⁴) double-excitation pool by active-space MP2 amplitude and keeping the top fraction shrinks the transformer vocabulary with negligible accuracy loss, where random pruning collapses. Deterministic CI-subspace test (CO/N₂/SiO, 12q): "),T("N₂ retains full-pool accuracy (2.26 mHa) keeping only 25% of doubles (vocabulary 1170→430) vs 50.4 mHa for random pruning at the same size (~22×)",{b:true}),T("; CO holds 3.7 mHa at 40% kept vs 29.7 mHa random.")],{after:30}),
  P([T("(4) Distributed hybrid workflow. ",{b:true}),T("Detailed in §4.")],{after:30}),
  P([T("Transfer learning — a generative prior that transfers across system size and chemistry. ",{b:true}),T("Using a canonical, frontier-relative tokenization (each excitation encoded as occupied-depth-below-HOMO and virtual-height-above-LUMO, independent of qubit count), a small system's token vocabulary is a provable subset of a larger one (H₆/12q ⊂ H₈/16q ⊂ H₁₀/20q). "),T("One GPT-QE generator trained only on H₄+H₆ (8q+12q) is deployed zero-shot across 16→56 qubits and, on the 3-seed mean, proposes determinant subspaces that beat random selection at every size",{b:true}),T(" — mean advantage +8.9/+8.3/+7.1/+5.8/+5.0/+4.4 mHa at 16/20/28/40/48/56q. We are explicit about robustness: the advantage is large and consistent at small sizes (all seeds positive at 16q) but narrows with scale and, beyond ~28q, is within run-to-run (3-seed) noise — it is a mean trend, not an every-seed guarantee (across the 18 size×seed pairs the generator wins 13/18). The more robust signal is variance reduction: the generator's selection spread across seeds is ~4× tighter than random's (≈4.7 vs ≈17.6 mHa) — reliable selection versus a lottery. This is the "),T("train-small, deploy-large",{i:true}),T(" idea: GQE training is the cost that is CPU-bound near ~16 qubits, so transferring a small-trained generator toward the 40q+ target — instead of training at scale — speaks directly to the scalability criterion. The enabler is a determinant-space evaluation (each proposed excitation maps by bitmask to a determinant; the Hamiltonian is diagonalized in that subspace via Slater-Condon, validated to 0.0000 mHa against the Jordan–Wigner engine) that needs no 2ⁿ statevector, so 56q runs on CPU. This is a "),T("selected-CI proxy",{i:true}),T(" for circuit-sampled QSCI (deterministic determinant construction, no shots), not executed QSCI. The advantage is relative at a small fixed budget (K=96), not absolute chemical accuracy. ")]),
  P([T("Cross-chemistry transfer (honest, partial). ",{b:true}),T("The same H-chain-trained generator, deployed to oxide active spaces (CO, SiO, BeO, SnO at 12q; CO, SnO at 20q), beats random on 4 of 6 targets (CO/SiO/CO-20q by +3–4 mHa, BeO a tie) but loses on SnO at both sizes (−2.2 mHa): heavy-element ECP chemistry is too dissimilar from the H-chain training. Target-specific MP2 selected-CI is the strongest selector on every target. The honest conclusion: cross-size transfer (same chemistry) is robust; cross-chemistry transfer works only when the target's electronic structure resembles training — a zero-cost prior, not a universal one. A same-size cross-molecule conditioning variant gave only a within-noise gain and is also reported as a negative.")]),

  new Paragraph({spacing:{before:50,after:10,line:240,lineRule:"auto"},alignment:AlignmentType.CENTER,
    children:[new ImageRun({type:"png",data:fs.readFileSync("../results/encoder/scaling_ladder.png"),transformation:{width:300,height:184}})]}),
  new Paragraph({spacing:{before:0,after:60,line:240,lineRule:"auto"},alignment:AlignmentType.CENTER,
    children:[new TextRun({text:"Figure 2. Train-small, deploy-large. A generator trained only on 8- and 12-qubit systems proposes lower-energy determinant subspaces than random selection at every target size up to 56 qubits, on the 3-seed mean (lower is better; determinant-space selected-CI / QSCI-proxy, matched budget K=96). Trained energies are tightly consistent across seeds (spread ~2 mHa); the mean advantage persists to 56q while narrowing into run-to-run noise at the largest sizes.",font:FONT,size:18,italics:true})]}),

  H("4. Hybrid Architecture"),
  P([T("The classical transformer trains on GPU (PyTorch); circuit evaluations are dispatched across GPUs via CUDA-Q's mqpu in an asynchronous generate→evaluate→update loop. Quantum resources handle state preparation and energy estimation (MPS / QSCI); classical resources handle generation, optimization, and active-space selection. Stage 1 is sampling-bound and parallelizable; Stage 2 is gradient-bound and adjoint-efficient.")]),
  new Paragraph({spacing:{before:60,after:20,line:240,lineRule:"auto"},alignment:AlignmentType.CENTER,
    children:[new ImageRun({type:"png",data:fs.readFileSync("matgenq_arch.png"),transformation:{width:320,height:228}})]}),
  new Paragraph({spacing:{before:0,after:60,line:240,lineRule:"auto"},alignment:AlignmentType.CENTER,
    children:[new TextRun({text:"Figure 1. MATGEN-Q hybrid architecture (target design): a classical generative transformer (Stage 1) and GPU-accelerated quantum simulation (MPS/QSCI) form an asynchronous loop; Stage 2 refines angles to chemical accuracy. The MPS tier and the GPU loop are the proposed Phase-3 GPU deliverable (not yet executed, §3, §5c); executed results in this submission use CPU selected-CI/QSCI and circuit-sampled QSCI to 20q.",font:FONT,size:18,italics:true})]}),

  H("5. Phase 3 Execution and Results"),
  P([T("Verified results (CPU; reproduced from a clean checkout via ",{b:true}),T("reproduce.py",{b:true,i:true}),T(").",{b:true}),T(" All values below are reproduced against the committed result files (Table 1).")],{after:50}),
  tbl1,
  new Paragraph({spacing:{before:30,after:50,line:240,lineRule:"auto"},children:[new TextRun({text:"Table 1. Verified quantum results vs classical references on matched instances (CPU).",font:FONT,size:19,italics:true})]}),
  P([T("Classical baseline and the exact wall (matched instances, timed). ",{b:true}),T("On identical STO-6G Hₙ geometries, classical FCI wall-clock grows ~24× from 20→24 qubits (0.33 s → 7.8 s) and is intractable by 32q on CPU; CCSD(T) stays cheap but its error climbs with correlation and breaks down under strong correlation (at H₂₄/48q, classical DMRG is itself 6.83 mHa off CCSD(T)). Exact quantum-state simulation needs ~16 TB at 40 qubits — the wall the MPS + QSCI tiers remove (Table 2).")],{after:50}),
  tbl2,
  new Paragraph({spacing:{before:30,after:50,line:240,lineRule:"auto"},children:[new TextRun({text:"Table 2. Classical reference cost on the Hₙ ladder (single-thread CPU) — the exact-method wall the quantum approach is measured against.",font:FONT,size:19,italics:true})]}),
  P([T("Scaling results targeted on qBraid GPU (owed — not yet executed). ",{b:true}),
     T("40-qubit MPS GQE/QSCI on H₂₀ (primary criterion): ",{b:true}),Q("[QBRAID-RUN: energy err vs DMRG, circuit depth, MPS bond dimension, shot budget, GPU wall-clock]"),
     T(" (CPU baseline today: operational, converging through 39 mHa). "),
     T("CrO/NiO near-38 qubits on GPU: ",{b:true}),Q("[QBRAID-RUN: accuracy achieved + wall-clock]"),
     T(", presented as the scaling demonstration on real open-shell chemistry, building on the executed 20-qubit results. "),
     T("Quantum-vs-classical wall-clock: ",{b:true}),Q("[QBRAID-RUN: MPS/QSCI vs exact statevector vs VQE]"),
     T(". "),T("Hardware validation: ",{b:true}),Q("[QBRAID-RUN: selected circuits on IonQ/IBM at 10–16 qubits, depth + shots]"),T(".")]),
  P([T("Determinant-budget sweep and a classical selected-CI baseline. ",{b:true}),T("Sweeping the selected-CI (QSCI-proxy) determinant budget K at 20q and 40q confirms the transfer advantage is budget-robust: the zero-shot generator beats random selection at essentially every K (e.g. 20q, K=64: 60.0 vs 73.2 mHa; 40q, K=64: 179.9 vs 189.4 mHa), converging to parity only at the largest 20q budget (K=128). As a classical baseline we add MP2-ranked selected-CI on the same determinant subspaces: using the target's own MP2 amplitudes it is the strongest selector (20q, K=64: 35.9 mHa), and a reciprocal-rank fusion of generator+MP2 does not improve on MP2 alone — the two signals are largely redundant. The honest reading: the transferred generator provides selection between random and target-specific MP2 at "),T("zero target-specific cost",{i:true}),T(" (a strong zero-shot prior for high-throughput screening), while MP2 selected-CI is the appropriate classical comparator where its per-candidate cost is affordable.")]),
  P([T("What the results establish. ",{b:true}),T("Three things are demonstrated, not asserted. (i) Correctness: the GQE/QSCI pipeline reproduces the classical FCI/CASCI reference to chemical accuracy on every instance we can run, including genuine open-shell multireference oxides (CrO, NiO) and EUV-relevant Sn-oxides. (ii) Scalability of the simulation layer: QSCI reaches chemical accuracy using a vanishing fraction of the CI space (3.8% at 20q, 0.15% at 28q), and operator-pool compression preserves accuracy at 25–40% of the double-excitation pool — both quantifying that the cost grows far slower than the Hilbert space. (iii) Transferable structure: a generator trained on small systems proposes good circuits for a larger one it never saw (§3), evidence that the learned policy — not just a per-system fit — scales. The honest boundary is that at the sizes classical FCI/DMRG still solve, we show correctness and favourable scaling rather than a head-to-head speed win; that win is the 40q+ regime the GPU run targets, where classical exact methods break down (Table 2).")]),

  P([T("Where it matters most: trust under strong correlation. ",{b:true}),T("Equilibrium benchmarks understate the problem — they live where classical methods already work. Stretching H₁₀ (20q) to dissociation drives genuine multireference character (Hartree–Fock weight in the exact wavefunction falls 0.93→0.06), and the classical gold standard fails qualitatively: CCSD(T) collapses "),T("non-variationally",{i:true}),T(" to 217 mHa BELOW the exact FCI energy at R=2.4 Å — a confidently wrong, unphysical answer. The determinant-subspace method (the QSCI principle, here via iterative selected-CI) instead "),T("reaches chemical accuracy with only ~500 determinants",{b:true}),T(" at every geometry across the dissociation, remaining a rigorous variational bound that is systematically convergent to the exact answer. This is the core value proposition: in the regime that matters for open-shell metal-oxide chemistry, the subspace approach is trustworthy where the classical gold standard is not. (Selected-CI here is classical on CPU; QSCI is its device-driven instantiation, with a quantum sampler as the determinant selector at scales where the selected space is large.) "),Q("[QBRAID-RUN: device-sampled selection at scale]")]),
  P([T("Proxy validated against real measurement; cost scaling. ",{b:true}),T("The scaling ladder uses a determinant-space selected-CI proxy; we confirm it tracks the real circuit-sampled pipeline by executing the measured QSCI (qml.sample, 3,000 shots × 160 circuits) at 16q and 20q — the measured energies match the proxy on the trained generator (16q: 26.6 vs 28.1 mHa; 20q: 49.3 vs 50.4 mHa), extending the genuinely-sampled pipeline beyond the prior 12-qubit point. We report one honest wrinkle: at this small shot budget (3,000 shots, K=600), diffuse random-circuit sampling collects more distinct determinants than the peaked generator and edges it on absolute energy under measurement (measured-random 24.0 / 46.7 vs measured-trained 28.1 / 50.4 mHa at 16q / 20q). This is a coverage effect at low shot count, not a generator-quality reversal: the deterministic proxy — which isolates per-determinant quality from sampling coverage — and the larger-budget determinant sweeps both favour the generator. The determinants needed for chemical accuracy grow ~1.38× per qubit versus 2.0× for the full FCI space (log-space R²=0.99) — a vanishing fraction (75% at 8q → 0.15% at 28q), though still exponential: at 40q+ the selected space reaches ~10⁶ determinants, the regime where device-driven selection becomes valuable. We do not claim polynomial scaling.")]),

  H("6. Platform Use and Resourcing"),
  P([T("qBraid provides classical (CPU/GPU) and quantum (QPU) credits. We use "),T("NVIDIA H100/A100 (80 GB)",{b:true}),T(" with CUDA-Q: tensornet-mps for the 24–40-qubit tier and cuStateVec for exact validation to ~32 qubits. One high-memory GPU suffices for MPS; 4–8 GPUs (NVLink) enable distributed circuit evaluation (pillar 4) and the >40-qubit bonus attempt; QPU (IonQ/IBM) for 10–16-qubit validation.")]),
  P([T("Resource estimate. ",{b:true}),T("UCC excitations decompose to ≤2-qubit gates; with operator-pool compression a length-8 generated circuit is shallow (tens of two-qubit gates), within MPS reach at bounded bond dimension near equilibrium. QSCI needs ~10³–10⁴ shots per circuit to resolve the dominant determinants (we use 2,000 in simulation). The dominant cost is the generate→evaluate loop: a few hundred transformer updates, each dispatching a batch of circuit evaluations across the GPU(s). We estimate ~1–2 weeks of single-GPU wall-clock for the full 24→40-qubit sweep plus the transition-metal-oxide runs; the workflow is backend-agnostic and degrades gracefully to fewer qubits if the allocation is smaller. Concrete per-run depth/shot/wall-clock: "),Q("[QBRAID-RUN: from §5]"),T(".")]),

  H("7. Limitations and Honest Scope"),
  P([T("We state where the approach does and does not yet provide benefit. (i) ",{}),T("Measurement vs proxy: ",{b:true}),T("the integrated GQE→QSCI loop is measured (real circuit sampling) at 12 qubits; the larger QSCI numbers use perturbative determinant selection as a hardware-independent proxy, validated against the 12-qubit measured pipeline — quantum-inspired at scale until executed with real sampling on qBraid. (ii) ",{}),T("No classical-beating claim yet: ",{b:true}),T("at ≤28 qubits classical FCI/DMRG already solve these instances, so we demonstrate correctness and favourable scaling, not a head-to-head speed advantage; that regime is 40q+ strong correlation where DMRG bond dimension explodes (visible at H₂₄/48q, where DMRG is 6.83 mHa off CCSD(T)). (iii) ",{}),T("40q is operational, not converged: ",{b:true}),T("on CPU the 40-qubit run converges through 39 mHa, above chemical accuracy; closing this is the GPU deliverable. (iv) ",{}),T("Transfer scope: ",{b:true}),T("cross-size transfer is a 3-seed-mean trend that narrows into noise beyond ~28q; cross-chemistry transfer works on 4 of 6 oxide targets and fails on the heaviest (SnO); target-specific MP2 beats the transferred prior. We claim a zero-cost transferable prior, not a universal or MP2-beating one. (v) ",{}),T("Strong-correlation regime: ",{b:true}),T("on stretched H₁₀ (HF weight 0.93→0.06), single-reference CCSD(T) collapses non-variationally to 217 mHa BELOW exact FCI — untrustworthy where it matters — while the determinant-subspace method stays a rigorous variational upper bound, systematically improvable with budget; reaching accuracy there needs the large-subspace (device-sampled) regime, motivating the quantum approach. A clear-eyed reading: MATGEN-Q is a working, reproducible pipeline whose scaling mechanisms are demonstrated and whose decisive large-scale quantum-vs-classical comparison is the executed GPU work this phase enables.")]),

  H("8. Conclusion and Reproducibility"),
  P([T("MATGEN-Q is a working two-stage GQE whose tensor-network and QSCI tiers, plus MP2 operator-pool compression, target the 40-qubit regime on a single GPU, with every claim third-party reproducible. A one-command driver ("),T("reproduce.py",{i:true}),T(") and a README with a “Launch on qBraid” button let judges re-run each headline result without modification.")]),

  new Paragraph({spacing:{before:120,after:40,line:240,lineRule:"auto"},pageBreakBefore:true,children:[new TextRun({text:"References",font:FONT,size:SZ,bold:true})]}),
];
function refP(n,txt){return new Paragraph({spacing:{after:30,line:240,lineRule:"auto"},indent:{left:360,hanging:360},children:[new TextRun({text:"["+n+"] ",font:FONT,size:20,bold:true}),new TextRun({text:txt,font:FONT,size:20})]});}
const refs=[
 refP(1,"K. Nakaji, et al. “The generative quantum eigensolver (GQE) and its application for ground state search.” arXiv:2401.09253 (2024). [AIST]"),
 refP(2,"N. P. D. Sawaya, et al. “HamLib: A library of Hamiltonians for benchmarking quantum algorithms and hardware.” Quantum 8, 1559 (2024)."),
 refP(3,"S. Minami, K. Nakaji, et al. “Generative quantum combinatorial optimization … conditional generative quantum eigensolver.” Digital Discovery 4(8) (2025)."),
 refP(4,"K. Kanno, et al. “Quantum-selected configuration interaction … subspaces selected by quantum computers.” arXiv:2302.11320 (2023)."),
 refP(5,"NVIDIA Corporation. CUDA-Q and cuQuantum SDK (cuStateVec, tensornet / tensornet-mps backends)."),
 refP(6,"J. Tilly, et al. “The Variational Quantum Eigensolver: A review of methods and best practices.” Physics Reports 986 (2022)."),
 refP(7,"P. Fare, et al. “A multi-fidelity machine learning approach to high-throughput materials screening.” npj Computational Materials 8, 257 (2022)."),
 refP(8,"T. D. Kharazi, et al. “Quantum Simulations for Extreme Ultraviolet Photolithography.” arXiv:2602.20234 (2026). [Xanadu & Mitsubishi Chemical]"),
 refP(9,"R. Kemmoku, Q. Gao, S. Kanno, et al. “Generative Circuit Design for Quantum-Selected Configuration Interaction.” arXiv:2604.09756 (2026). [Mitsubishi Chemical]"),
];
children.push(...refs);

const doc=new Document({
  styles:{default:{document:{run:{font:FONT,size:SZ}}}},
  sections:[{properties:{page:{size:{width:12240,height:15840},margin:{top:1224,right:1224,bottom:1224,left:1224}}},children}]
});
Packer.toBuffer(doc).then(b=>{fs.writeFileSync("EIGENNEXUS_Phase3_Content.docx",b);console.log("Created EIGENNEXUS_Phase3_Content.docx:",b.length,"bytes");});
